# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activestorage` gem.
# Please instead update this file by running `bin/tapioca gem activestorage`.


# :markup: markdown
# :include: ../README.md
#
# pkg:gem/activestorage#lib/active_storage/gem_version.rb:3
module ActiveStorage
  extend ::ActiveSupport::Autoload

  # pkg:gem/activestorage#lib/active_storage.rb:58
  def analyzers; end

  # pkg:gem/activestorage#lib/active_storage.rb:58
  def analyzers=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:64
  def binary_content_type; end

  # pkg:gem/activestorage#lib/active_storage.rb:64
  def binary_content_type=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:66
  def content_types_allowed_inline; end

  # pkg:gem/activestorage#lib/active_storage.rb:66
  def content_types_allowed_inline=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:65
  def content_types_to_serve_as_binary; end

  # pkg:gem/activestorage#lib/active_storage.rb:65
  def content_types_to_serve_as_binary=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:362
  def draw_routes; end

  # pkg:gem/activestorage#lib/active_storage.rb:362
  def draw_routes=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:49
  def logger; end

  # pkg:gem/activestorage#lib/active_storage.rb:49
  def logger=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:60
  def paths; end

  # pkg:gem/activestorage#lib/active_storage.rb:60
  def paths=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:57
  def previewers; end

  # pkg:gem/activestorage#lib/active_storage.rb:57
  def previewers=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:55
  def queues; end

  # pkg:gem/activestorage#lib/active_storage.rb:55
  def queues=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:363
  def resolve_model_to_route; end

  # pkg:gem/activestorage#lib/active_storage.rb:363
  def resolve_model_to_route=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:361
  def routes_prefix; end

  # pkg:gem/activestorage#lib/active_storage.rb:361
  def routes_prefix=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:357
  def service_urls_expire_in; end

  # pkg:gem/activestorage#lib/active_storage.rb:357
  def service_urls_expire_in=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:356
  def streaming_chunk_max_size; end

  # pkg:gem/activestorage#lib/active_storage.rb:356
  def streaming_chunk_max_size=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:68
  def supported_image_processing_methods; end

  # pkg:gem/activestorage#lib/active_storage.rb:68
  def supported_image_processing_methods=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:358
  def touch_attachment_records; end

  # pkg:gem/activestorage#lib/active_storage.rb:358
  def touch_attachment_records=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:365
  def track_variants; end

  # pkg:gem/activestorage#lib/active_storage.rb:365
  def track_variants=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:354
  def unsupported_image_processing_arguments; end

  # pkg:gem/activestorage#lib/active_storage.rb:354
  def unsupported_image_processing_arguments=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:359
  def urls_expire_in; end

  # pkg:gem/activestorage#lib/active_storage.rb:359
  def urls_expire_in=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:62
  def variable_content_types; end

  # pkg:gem/activestorage#lib/active_storage.rb:62
  def variable_content_types=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:51
  def variant_processor; end

  # pkg:gem/activestorage#lib/active_storage.rb:51
  def variant_processor=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:53
  def variant_transformer; end

  # pkg:gem/activestorage#lib/active_storage.rb:53
  def variant_transformer=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:50
  def verifier; end

  # pkg:gem/activestorage#lib/active_storage.rb:50
  def verifier=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:379
  def video_preview_arguments; end

  # pkg:gem/activestorage#lib/active_storage.rb:379
  def video_preview_arguments=(val); end

  # pkg:gem/activestorage#lib/active_storage.rb:63
  def web_image_content_types; end

  # pkg:gem/activestorage#lib/active_storage.rb:63
  def web_image_content_types=(val); end

  class << self
    # pkg:gem/activestorage#lib/active_storage.rb:58
    def analyzers; end

    # pkg:gem/activestorage#lib/active_storage.rb:58
    def analyzers=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:64
    def binary_content_type; end

    # pkg:gem/activestorage#lib/active_storage.rb:64
    def binary_content_type=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:367
    def checksum_implementation; end

    # pkg:gem/activestorage#lib/active_storage.rb:367
    def checksum_implementation=(_arg0); end

    # pkg:gem/activestorage#lib/active_storage.rb:66
    def content_types_allowed_inline; end

    # pkg:gem/activestorage#lib/active_storage.rb:66
    def content_types_allowed_inline=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:65
    def content_types_to_serve_as_binary; end

    # pkg:gem/activestorage#lib/active_storage.rb:65
    def content_types_to_serve_as_binary=(val); end

    # pkg:gem/activestorage#lib/active_storage/deprecator.rb:4
    def deprecator; end

    # pkg:gem/activestorage#lib/active_storage.rb:362
    def draw_routes; end

    # pkg:gem/activestorage#lib/active_storage.rb:362
    def draw_routes=(val); end

    # Returns the currently loaded version of Active Storage as a +Gem::Version+.
    #
    # pkg:gem/activestorage#lib/active_storage/gem_version.rb:5
    def gem_version; end

    # pkg:gem/activestorage#lib/active_storage.rb:49
    def logger; end

    # pkg:gem/activestorage#lib/active_storage.rb:49
    def logger=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:60
    def paths; end

    # pkg:gem/activestorage#lib/active_storage.rb:60
    def paths=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:57
    def previewers; end

    # pkg:gem/activestorage#lib/active_storage.rb:57
    def previewers=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:55
    def queues; end

    # pkg:gem/activestorage#lib/active_storage.rb:55
    def queues=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:363
    def resolve_model_to_route; end

    # pkg:gem/activestorage#lib/active_storage.rb:363
    def resolve_model_to_route=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:361
    def routes_prefix; end

    # pkg:gem/activestorage#lib/active_storage.rb:361
    def routes_prefix=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:357
    def service_urls_expire_in; end

    # pkg:gem/activestorage#lib/active_storage.rb:357
    def service_urls_expire_in=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:356
    def streaming_chunk_max_size; end

    # pkg:gem/activestorage#lib/active_storage.rb:356
    def streaming_chunk_max_size=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:376
    def streaming_max_ranges; end

    # pkg:gem/activestorage#lib/active_storage.rb:376
    def streaming_max_ranges=(_arg0); end

    # pkg:gem/activestorage#lib/active_storage.rb:68
    def supported_image_processing_methods; end

    # pkg:gem/activestorage#lib/active_storage.rb:68
    def supported_image_processing_methods=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:358
    def touch_attachment_records; end

    # pkg:gem/activestorage#lib/active_storage.rb:358
    def touch_attachment_records=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:365
    def track_variants; end

    # pkg:gem/activestorage#lib/active_storage.rb:365
    def track_variants=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:354
    def unsupported_image_processing_arguments; end

    # pkg:gem/activestorage#lib/active_storage.rb:354
    def unsupported_image_processing_arguments=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:359
    def urls_expire_in; end

    # pkg:gem/activestorage#lib/active_storage.rb:359
    def urls_expire_in=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:62
    def variable_content_types; end

    # pkg:gem/activestorage#lib/active_storage.rb:62
    def variable_content_types=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:51
    def variant_processor; end

    # pkg:gem/activestorage#lib/active_storage.rb:51
    def variant_processor=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:53
    def variant_transformer; end

    # pkg:gem/activestorage#lib/active_storage.rb:53
    def variant_transformer=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:50
    def verifier; end

    # pkg:gem/activestorage#lib/active_storage.rb:50
    def verifier=(val); end

    # Returns the currently loaded version of Active Storage as a +Gem::Version+.
    #
    # pkg:gem/activestorage#lib/active_storage/version.rb:7
    def version; end

    # pkg:gem/activestorage#lib/active_storage.rb:379
    def video_preview_arguments; end

    # pkg:gem/activestorage#lib/active_storage.rb:379
    def video_preview_arguments=(val); end

    # pkg:gem/activestorage#lib/active_storage.rb:63
    def web_image_content_types; end

    # pkg:gem/activestorage#lib/active_storage.rb:63
    def web_image_content_types=(val); end
  end
end

# = Active Storage \Analyzer
#
# This is an abstract base class for analyzers, which extract metadata from blobs. See
# ActiveStorage::Analyzer::VideoAnalyzer for an example of a concrete subclass.
#
# pkg:gem/activestorage#lib/active_storage/analyzer.rb:8
class ActiveStorage::Analyzer
  # pkg:gem/activestorage#lib/active_storage/analyzer.rb:23
  def initialize(blob); end

  # pkg:gem/activestorage#lib/active_storage/analyzer.rb:9
  def blob; end

  # Override this method in a concrete subclass. Have it return a Hash of metadata.
  #
  # pkg:gem/activestorage#lib/active_storage/analyzer.rb:28
  def metadata; end

  private

  # Downloads the blob to a tempfile on disk. Yields the tempfile.
  #
  # pkg:gem/activestorage#lib/active_storage/analyzer.rb:34
  def download_blob_to_tempfile(&block); end

  # pkg:gem/activestorage#lib/active_storage/analyzer.rb:46
  def instrument(analyzer, &block); end

  # pkg:gem/activestorage#lib/active_storage/analyzer.rb:38
  def logger; end

  # pkg:gem/activestorage#lib/active_storage/analyzer.rb:42
  def tmpdir; end

  class << self
    # Implement this method in a concrete subclass. Have it return true when given a blob from which
    # the analyzer can extract metadata.
    #
    # pkg:gem/activestorage#lib/active_storage/analyzer.rb:13
    def accept?(blob); end

    # Implement this method in concrete subclasses. It will determine if blob analysis
    # should be done in a job or performed inline. By default, analysis is enqueued in a job.
    #
    # pkg:gem/activestorage#lib/active_storage/analyzer.rb:19
    def analyze_later?; end
  end
end

# = Active Storage \Attached
#
# Abstract base class for the concrete ActiveStorage::Attached::One and ActiveStorage::Attached::Many
# classes that both provide proxy access to the blob association for a record.
#
# pkg:gem/activestorage#lib/active_storage/attached.rb:9
class ActiveStorage::Attached
  # pkg:gem/activestorage#lib/active_storage/attached.rb:12
  def initialize(name, record); end

  # pkg:gem/activestorage#lib/active_storage/attached.rb:10
  def name; end

  # pkg:gem/activestorage#lib/active_storage/attached.rb:10
  def record; end

  private

  # pkg:gem/activestorage#lib/active_storage/attached.rb:17
  def change; end
end

# pkg:gem/activestorage#lib/active_storage/attached/changes.rb:4
module ActiveStorage::Attached::Changes
  extend ::ActiveSupport::Autoload
end

# pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:4
class ActiveStorage::Attached::Changes::CreateMany
  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:7
  def initialize(name, record, attachables, pending_uploads: T.unsafe(nil)); end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:5
  def attachables; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:14
  def attachments; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:18
  def blobs; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:5
  def name; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:5
  def pending_uploads; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:5
  def record; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:26
  def save; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:22
  def upload; end

  private

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:44
  def assign_associated_attachments; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:36
  def build_subchange_from(attachable); end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:52
  def persisted_or_new_attachments; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:48
  def reset_associated_blobs; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:32
  def subchanges; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_many.rb:40
  def subchanges_without_blobs; end
end

# pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:7
class ActiveStorage::Attached::Changes::CreateOne
  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:10
  def initialize(name, record, attachable); end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:8
  def attachable; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:15
  def attachment; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:19
  def blob; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:8
  def name; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:8
  def record; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:48
  def save; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:23
  def upload; end

  private

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:120
  def attachment_service_name; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:64
  def build_attachment; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:58
  def find_attachment; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:54
  def find_or_build_attachment; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one.rb:68
  def find_or_build_blob; end
end

# pkg:gem/activestorage#lib/active_storage/attached/changes/create_one_of_many.rb:4
class ActiveStorage::Attached::Changes::CreateOneOfMany < ::ActiveStorage::Attached::Changes::CreateOne
  private

  # pkg:gem/activestorage#lib/active_storage/attached/changes/create_one_of_many.rb:6
  def find_attachment; end
end

# pkg:gem/activestorage#lib/active_storage/attached/changes/delete_many.rb:4
class ActiveStorage::Attached::Changes::DeleteMany
  # pkg:gem/activestorage#lib/active_storage/attached/changes/delete_many.rb:7
  def initialize(name, record); end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/delete_many.rb:11
  def attachables; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/delete_many.rb:15
  def attachments; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/delete_many.rb:19
  def blobs; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/delete_many.rb:5
  def name; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/delete_many.rb:5
  def record; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/delete_many.rb:23
  def save; end
end

# pkg:gem/activestorage#lib/active_storage/attached/changes/delete_one.rb:4
class ActiveStorage::Attached::Changes::DeleteOne
  # pkg:gem/activestorage#lib/active_storage/attached/changes/delete_one.rb:7
  def initialize(name, record); end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/delete_one.rb:11
  def attachment; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/delete_one.rb:5
  def name; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/delete_one.rb:5
  def record; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/delete_one.rb:15
  def save; end
end

# pkg:gem/activestorage#lib/active_storage/attached/changes/detach_many.rb:4
class ActiveStorage::Attached::Changes::DetachMany
  # pkg:gem/activestorage#lib/active_storage/attached/changes/detach_many.rb:7
  def initialize(name, record, attachments); end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/detach_many.rb:5
  def attachments; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/detach_many.rb:11
  def detach; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/detach_many.rb:5
  def name; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/detach_many.rb:5
  def record; end
end

# pkg:gem/activestorage#lib/active_storage/attached/changes/detach_one.rb:4
class ActiveStorage::Attached::Changes::DetachOne
  # pkg:gem/activestorage#lib/active_storage/attached/changes/detach_one.rb:7
  def initialize(name, record, attachment); end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/detach_one.rb:5
  def attachment; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/detach_one.rb:11
  def detach; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/detach_one.rb:5
  def name; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/detach_one.rb:5
  def record; end

  private

  # pkg:gem/activestorage#lib/active_storage/attached/changes/detach_one.rb:19
  def reset; end
end

# pkg:gem/activestorage#lib/active_storage/attached/changes/purge_many.rb:4
class ActiveStorage::Attached::Changes::PurgeMany
  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_many.rb:7
  def initialize(name, record, attachments); end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_many.rb:5
  def attachments; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_many.rb:5
  def name; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_many.rb:11
  def purge; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_many.rb:16
  def purge_later; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_many.rb:5
  def record; end

  private

  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_many.rb:22
  def reset; end
end

# pkg:gem/activestorage#lib/active_storage/attached/changes/purge_one.rb:4
class ActiveStorage::Attached::Changes::PurgeOne
  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_one.rb:7
  def initialize(name, record, attachment); end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_one.rb:5
  def attachment; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_one.rb:5
  def name; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_one.rb:11
  def purge; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_one.rb:16
  def purge_later; end

  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_one.rb:5
  def record; end

  private

  # pkg:gem/activestorage#lib/active_storage/attached/changes/purge_one.rb:22
  def reset; end
end

# = Active Storage \Attached \Many
#
# Decorated proxy object representing of multiple attachments to a model.
#
# pkg:gem/activestorage#lib/active_storage/attached/many.rb:7
class ActiveStorage::Attached::Many < ::ActiveStorage::Attached
  # Attaches one or more +attachables+ to the record.
  #
  # If the record is persisted and unchanged, the attachments are saved to
  # the database immediately. Otherwise, they'll be saved to the DB when the
  # record is next saved.
  #
  #   document.images.attach(params[:images]) # Array of ActionDispatch::Http::UploadedFile objects
  #   document.images.attach(params[:signed_blob_id]) # Signed reference to blob from direct upload
  #   document.images.attach(io: File.open("/path/to/racecar.jpg"), filename: "racecar.jpg", content_type: "image/jpeg")
  #   document.images.attach([ first_blob, second_blob ])
  #
  # pkg:gem/activestorage#lib/active_storage/attached/many.rb:51
  def attach(*attachables); end

  # Returns true if any attachments have been made.
  #
  #   class Gallery < ApplicationRecord
  #     has_many_attached :photos
  #   end
  #
  #   Gallery.new.photos.attached? # => false
  #
  # pkg:gem/activestorage#lib/active_storage/attached/many.rb:66
  def attached?; end

  # Returns all the associated attachment records.
  #
  # All methods called on this proxy object that aren't listed here will automatically be delegated to +attachments+.
  #
  # pkg:gem/activestorage#lib/active_storage/attached/many.rb:32
  def attachments; end

  # Returns all attached blobs.
  #
  # pkg:gem/activestorage#lib/active_storage/attached/many.rb:37
  def blobs; end

  # pkg:gem/activestorage#lib/active_storage/attached/many.rb:25
  def detach(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/activestorage#lib/active_storage/attached/many.rb:27
  def method_missing(method, *_arg1, **_arg2, &_arg3); end

  # pkg:gem/activestorage#lib/active_storage/attached/many.rb:13
  def purge(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/activestorage#lib/active_storage/attached/many.rb:19
  def purge_later(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/activestorage#lib/active_storage/attached/many.rb:75
  def detach_many; end

  # pkg:gem/activestorage#lib/active_storage/attached/many.rb:71
  def purge_many; end

  # pkg:gem/activestorage#lib/active_storage/attached/many.rb:27
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
end

# = Active Storage \Attached \Model
#
# Provides the class-level DSL for declaring an Active Record model's attachments.
#
# pkg:gem/activestorage#lib/active_storage/attached/model.rb:9
module ActiveStorage::Attached::Model
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActiveStorage::Attached::Model::ClassMethods

  # pkg:gem/activestorage#lib/active_storage/attached/model.rb:281
  def attachment_changes; end

  # pkg:gem/activestorage#lib/active_storage/attached/model.rb:285
  def changed_for_autosave?; end

  # pkg:gem/activestorage#lib/active_storage/attached/model.rb:295
  def reload(*_arg0); end

  private

  # pkg:gem/activestorage#lib/active_storage/attached/model.rb:289
  def initialize_dup(*_arg0); end

  class << self
    # pkg:gem/activestorage#lib/active_storage/attached/model.rb:263
    def validate_service_configuration(service_name, model_class, association_name); end

    private

    # pkg:gem/activestorage#lib/active_storage/attached/model.rb:274
    def validate_global_service_configuration(model_class); end
  end
end

# pkg:gem/activestorage#lib/active_storage/attached/model.rb:54
module ActiveStorage::Attached::Model::ClassMethods
  # pkg:gem/activestorage#lib/active_storage/attached/model.rb:210
  def has_many_attached(name, dependent: T.unsafe(nil), service: T.unsafe(nil), strict_loading: T.unsafe(nil)); end

  # pkg:gem/activestorage#lib/active_storage/attached/model.rb:108
  def has_one_attached(name, dependent: T.unsafe(nil), service: T.unsafe(nil), strict_loading: T.unsafe(nil)); end
end

# = Active Storage \Attached \One
#
# Representation of a single attachment to a model.
#
# pkg:gem/activestorage#lib/active_storage/attached/one.rb:7
class ActiveStorage::Attached::One < ::ActiveStorage::Attached
  # Attaches an +attachable+ to the record.
  #
  # If the record is persisted and unchanged, the attachment is saved to
  # the database immediately. Otherwise, it'll be saved to the DB when the
  # record is next saved.
  #
  #   person.avatar.attach(params[:avatar]) # ActionDispatch::Http::UploadedFile object
  #   person.avatar.attach(params[:signed_blob_id]) # Signed reference to blob from direct upload
  #   person.avatar.attach(io: File.open("/path/to/face.jpg"), filename: "face.jpg", content_type: "image/jpeg")
  #   person.avatar.attach(avatar_blob) # ActiveStorage::Blob object
  #
  # pkg:gem/activestorage#lib/active_storage/attached/one.rb:58
  def attach(attachable); end

  # Returns +true+ if an attachment has been made.
  #
  #   class User < ApplicationRecord
  #     has_one_attached :avatar
  #   end
  #
  #   User.new.avatar.attached? # => false
  #
  # pkg:gem/activestorage#lib/active_storage/attached/one.rb:73
  def attached?; end

  # Returns the associated attachment record.
  #
  # You don't have to call this method to access the attachment's methods as
  # they are all available at the model level.
  #
  # pkg:gem/activestorage#lib/active_storage/attached/one.rb:33
  def attachment; end

  # Returns +true+ if an attachment is not attached.
  #
  #   class User < ApplicationRecord
  #     has_one_attached :avatar
  #   end
  #
  #   User.new.avatar.blank? # => true
  #
  # pkg:gem/activestorage#lib/active_storage/attached/one.rb:44
  def blank?; end

  # pkg:gem/activestorage#lib/active_storage/attached/one.rb:25
  def detach(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/activestorage#lib/active_storage/attached/one.rb:27
  def method_missing(method, *_arg1, **_arg2, &_arg3); end

  # pkg:gem/activestorage#lib/active_storage/attached/one.rb:13
  def purge(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/activestorage#lib/active_storage/attached/one.rb:19
  def purge_later(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/activestorage#lib/active_storage/attached/one.rb:82
  def detach_one; end

  # pkg:gem/activestorage#lib/active_storage/attached/one.rb:78
  def purge_one; end

  # pkg:gem/activestorage#lib/active_storage/attached/one.rb:27
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
end

# pkg:gem/activestorage#lib/active_storage/downloader.rb:4
class ActiveStorage::Downloader
  # pkg:gem/activestorage#lib/active_storage/downloader.rb:7
  def initialize(service); end

  # pkg:gem/activestorage#lib/active_storage/downloader.rb:11
  def open(key, checksum: T.unsafe(nil), verify: T.unsafe(nil), name: T.unsafe(nil), tmpdir: T.unsafe(nil)); end

  # pkg:gem/activestorage#lib/active_storage/downloader.rb:5
  def service; end

  private

  # pkg:gem/activestorage#lib/active_storage/downloader.rb:30
  def download(key, file); end

  # pkg:gem/activestorage#lib/active_storage/downloader.rb:20
  def open_tempfile(name, tmpdir = T.unsafe(nil)); end

  # pkg:gem/activestorage#lib/active_storage/downloader.rb:37
  def verify_integrity_of(file, checksum:); end
end

# Generic base class for all Active Storage exceptions.
#
# pkg:gem/activestorage#lib/active_storage/errors.rb:5
class ActiveStorage::Error < ::StandardError; end

# Raised when ActiveStorage::Blob#download is called on a blob where the
# backing file is no longer present in its service.
#
# pkg:gem/activestorage#lib/active_storage/errors.rb:25
class ActiveStorage::FileNotFoundError < ::ActiveStorage::Error; end

# = Active Storage \FixtureSet
#
# Fixtures are a way of organizing data that you want to test against; in
# short, sample data.
#
# To learn more about fixtures, read the ActiveRecord::FixtureSet documentation.
#
# === YAML
#
# Like other Active Record-backed models, ActiveStorage::Attachment and
# ActiveStorage::Blob records inherit from ActiveRecord::Base instances and
# therefore can be populated by fixtures.
#
# Consider a hypothetical <tt>Article</tt> model class, its related
# fixture data, as well as fixture data for related ActiveStorage::Attachment
# and ActiveStorage::Blob records:
#
#   # app/models/article.rb
#   class Article < ApplicationRecord
#     has_one_attached :thumbnail
#   end
#
# <code></code>
#
#   # fixtures/active_storage/blobs.yml
#   first_thumbnail_blob: <%= ActiveStorage::FixtureSet.blob filename: "first.png" %>
#
# <code></code>
#
#   # fixtures/active_storage/attachments.yml
#   first_thumbnail_attachment:
#     name: thumbnail
#     record: first (Article)
#     blob: first_thumbnail_blob
#
# When processed, Active Record will insert database records for each fixture
# entry and will ensure the Active Storage relationship is intact.
#
# pkg:gem/activestorage#lib/active_storage/fixture_set.rb:44
class ActiveStorage::FixtureSet
  include ::ActiveSupport::Testing::FileFixtures
  include ::ActiveRecord::SecureToken
  extend ::ActiveRecord::SecureToken::ClassMethods

  # pkg:gem/activestorage#lib/active_storage/fixture_set.rb:45
  def file_fixture_path; end

  # pkg:gem/activestorage#lib/active_storage/fixture_set.rb:45
  def file_fixture_path?; end

  # pkg:gem/activestorage#lib/active_storage/fixture_set.rb:70
  def prepare(instance, **attributes); end

  class << self
    # Generate a YAML-encoded representation of an ActiveStorage::Blob
    # instance's attributes, resolve the file relative to the directory mentioned
    # by ActiveSupport::Testing::FileFixtures.file_fixture, and upload
    # the file to the Service
    #
    # ==== Examples
    #
    #   # tests/fixtures/active_storage/blobs.yml
    #   second_thumbnail_blob: <%= ActiveStorage::FixtureSet.blob(
    #     filename: "second.svg",
    #   ) %>
    #
    #   third_thumbnail_blob: <%= ActiveStorage::FixtureSet.blob(
    #     filename: "third.svg",
    #     content_type: "image/svg+xml",
    #     service_name: "public"
    #   ) %>
    #
    # pkg:gem/activestorage#lib/active_storage/fixture_set.rb:66
    def blob(filename:, **attributes); end

    # pkg:gem/activestorage#lib/active_storage/fixture_set.rb:45
    def file_fixture_path; end

    # pkg:gem/activestorage#lib/active_storage/fixture_set.rb:45
    def file_fixture_path=(value); end

    # pkg:gem/activestorage#lib/active_storage/fixture_set.rb:45
    def file_fixture_path?; end

    private

    # pkg:gem/activestorage#lib/active_storage/fixture_set.rb:45
    def __class_attr_file_fixture_path; end

    # pkg:gem/activestorage#lib/active_storage/fixture_set.rb:45
    def __class_attr_file_fixture_path=(new_value); end
  end
end

# Raised when uploaded or downloaded data does not match a precomputed checksum.
# Indicates that a network error or a software bug caused data corruption.
#
# pkg:gem/activestorage#lib/active_storage/errors.rb:21
class ActiveStorage::IntegrityError < ::ActiveStorage::Error; end

# Raised when a storage key resolves to a path outside the service's root
# directory, indicating a potential path traversal attack.
#
# pkg:gem/activestorage#lib/active_storage/errors.rb:32
class ActiveStorage::InvalidKeyError < ::ActiveStorage::Error; end

# Raised when ActiveStorage::Blob#variant is called on a blob that isn't variable.
# Use ActiveStorage::Blob#variable? to determine whether a blob is variable.
#
# pkg:gem/activestorage#lib/active_storage/errors.rb:9
class ActiveStorage::InvariableError < ::ActiveStorage::Error; end

# pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:6
class ActiveStorage::LogSubscriber < ::ActiveSupport::LogSubscriber
  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:53
  def logger; end

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:21
  def preview(event); end

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:26
  def service_delete(event); end

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:31
  def service_delete_prefixed(event); end

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:14
  def service_download(event); end

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:36
  def service_exist(event); end

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:46
  def service_mirror(event); end

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:19
  def service_streaming_download(event); end

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:7
  def service_upload(event); end

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:41
  def service_url(event); end

  private

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:62
  def debug(event, colored_message); end

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:58
  def info(event, colored_message); end

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:70
  def key_in(event); end

  # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:66
  def log_prefix_for_service(event); end

  class << self
    private

    # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:12
    def __class_attr_log_levels; end

    # pkg:gem/activestorage#lib/active_storage/log_subscriber.rb:12
    def __class_attr_log_levels=(new_value); end
  end
end

# Raised when a Previewer is unable to generate a preview image.
#
# pkg:gem/activestorage#lib/active_storage/errors.rb:28
class ActiveStorage::PreviewError < ::ActiveStorage::Error; end

# = Active Storage \Previewer
#
# This is an abstract base class for previewers, which generate images from blobs. See
# ActiveStorage::Previewer::MuPDFPreviewer and ActiveStorage::Previewer::VideoPreviewer for
# examples of concrete subclasses.
#
# pkg:gem/activestorage#lib/active_storage/previewer.rb:9
class ActiveStorage::Previewer
  # pkg:gem/activestorage#lib/active_storage/previewer.rb:18
  def initialize(blob); end

  # pkg:gem/activestorage#lib/active_storage/previewer.rb:10
  def blob; end

  # Override this method in a concrete subclass. Have it yield an attachable preview image (i.e.
  # anything accepted by ActiveStorage::Attached::One#attach). Pass the additional options to
  # the underlying blob that is created.
  #
  # pkg:gem/activestorage#lib/active_storage/previewer.rb:25
  def preview(**options); end

  private

  # pkg:gem/activestorage#lib/active_storage/previewer.rb:78
  def capture(*argv, to:); end

  # Downloads the blob to a tempfile on disk. Yields the tempfile.
  #
  # pkg:gem/activestorage#lib/active_storage/previewer.rb:31
  def download_blob_to_tempfile(&block); end

  # Executes a system command, capturing its binary output in a tempfile. Yields the tempfile.
  #
  # Use this method to shell out to a system library (e.g. muPDF or FFmpeg) for preview image
  # generation. The resulting tempfile can be used as the +:io+ value in an attachable Hash:
  #
  #   def preview
  #     download_blob_to_tempfile do |input|
  #       draw "my-drawing-command", input.path, "--format", "png", "-" do |output|
  #         yield io: output, filename: "#{blob.filename.base}.png", content_type: "image/png"
  #       end
  #     end
  #   end
  #
  # The output tempfile is opened in the directory returned by #tmpdir.
  #
  # pkg:gem/activestorage#lib/active_storage/previewer.rb:49
  def draw(*argv); end

  # pkg:gem/activestorage#lib/active_storage/previewer.rb:69
  def instrument(operation, payload = T.unsafe(nil), &block); end

  # pkg:gem/activestorage#lib/active_storage/previewer.rb:93
  def logger; end

  # pkg:gem/activestorage#lib/active_storage/previewer.rb:59
  def open_tempfile; end

  # pkg:gem/activestorage#lib/active_storage/previewer.rb:73
  def service_name; end

  # pkg:gem/activestorage#lib/active_storage/previewer.rb:97
  def tmpdir; end

  class << self
    # Implement this method in a concrete subclass. Have it return true when given a blob from which
    # the previewer can generate an image.
    #
    # pkg:gem/activestorage#lib/active_storage/previewer.rb:14
    def accept?(blob); end
  end
end

# = Active Storage \Service
#
# Abstract class serving as an interface for concrete services.
#
# The available services are:
#
# * +Disk+, to manage attachments saved directly on the hard drive.
# * +GCS+, to manage attachments through Google Cloud Storage.
# * +S3+, to manage attachments through Amazon S3.
# * +Mirror+, to be able to use several services to manage attachments.
#
# Inside a \Rails application, you can set-up your services through the
# generated <tt>config/storage.yml</tt> file and reference one
# of the aforementioned constant under the +service+ key. For example:
#
#   local:
#     service: Disk
#     root: <%= Rails.root.join("storage") %>
#
# You can checkout the service's constructor to know which keys are required.
#
# Then, in your application's configuration, you can specify the service to
# use like this:
#
#   config.active_storage.service = :local
#
# If you are using Active Storage outside of a Ruby on \Rails application, you
# can configure the service to use like this:
#
#   ActiveStorage::Blob.service = ActiveStorage::Service.configure(
#     :local,
#     { local: {service: "Disk",  root: Pathname("/tmp/foo/storage") } }
#   )
#
# pkg:gem/activestorage#lib/active_storage/service.rb:43
class ActiveStorage::Service
  extend ::ActiveSupport::Autoload

  # Concatenate multiple files into a single "composed" file.
  #
  # pkg:gem/activestorage#lib/active_storage/service.rb:96
  def compose(source_keys, destination_key, filename: T.unsafe(nil), content_type: T.unsafe(nil), disposition: T.unsafe(nil), custom_metadata: T.unsafe(nil)); end

  # Delete the file at the +key+.
  #
  # pkg:gem/activestorage#lib/active_storage/service.rb:101
  def delete(key); end

  # Delete files at keys starting with the +prefix+.
  #
  # pkg:gem/activestorage#lib/active_storage/service.rb:106
  def delete_prefixed(prefix); end

  # Return the content of the file at the +key+.
  #
  # pkg:gem/activestorage#lib/active_storage/service.rb:82
  def download(key); end

  # Return the partial content in the byte +range+ of the file at the +key+.
  #
  # pkg:gem/activestorage#lib/active_storage/service.rb:87
  def download_chunk(key, range); end

  # Return +true+ if a file exists at the +key+.
  #
  # pkg:gem/activestorage#lib/active_storage/service.rb:111
  def exist?(key); end

  # Returns a Hash of headers for +url_for_direct_upload+ requests.
  #
  # pkg:gem/activestorage#lib/active_storage/service.rb:143
  def headers_for_direct_upload(key, filename:, content_type:, content_length:, checksum:, custom_metadata: T.unsafe(nil)); end

  # pkg:gem/activestorage#lib/active_storage/service.rb:151
  def inspect; end

  # pkg:gem/activestorage#lib/active_storage/service.rb:46
  def name; end

  # pkg:gem/activestorage#lib/active_storage/service.rb:46
  def name=(_arg0); end

  # pkg:gem/activestorage#lib/active_storage/service.rb:91
  def open(*args, **options, &block); end

  # pkg:gem/activestorage#lib/active_storage/service.rb:147
  def public?; end

  # Update metadata for the file identified by +key+ in the service.
  # Override in subclasses only if the service needs to store specific
  # metadata that has to be updated upon identification.
  #
  # pkg:gem/activestorage#lib/active_storage/service.rb:78
  def update_metadata(key, **metadata); end

  # Upload the +io+ to the +key+ specified. If a +checksum+ is provided, the service will
  # ensure a match when the upload has completed or raise an ActiveStorage::IntegrityError.
  #
  # pkg:gem/activestorage#lib/active_storage/service.rb:71
  def upload(key, io, checksum: T.unsafe(nil), **options); end

  # Returns the URL for the file at the +key+. This returns a permanent URL for public files, and returns a
  # short-lived URL for private files. For private files you can provide the +disposition+ (+:inline+ or +:attachment+),
  # +filename+, and +content_type+ that you wish the file to be served with on request. Additionally, you can also provide
  # the amount of seconds the URL will be valid for, specified in +expires_in+.
  #
  # pkg:gem/activestorage#lib/active_storage/service.rb:119
  def url(key, **options); end

  # Returns a signed, temporary URL that a direct upload file can be PUT to on the +key+.
  # The URL will be valid for the amount of seconds specified in +expires_in+.
  # You must also provide the +content_type+, +content_length+, and +checksum+ of the file
  # that will be uploaded. All these attributes will be validated by the service upon upload.
  #
  # pkg:gem/activestorage#lib/active_storage/service.rb:138
  def url_for_direct_upload(key, expires_in:, content_type:, content_length:, checksum:, custom_metadata: T.unsafe(nil)); end

  private

  # pkg:gem/activestorage#lib/active_storage/service.rb:179
  def content_disposition_with(filename:, type: T.unsafe(nil)); end

  # pkg:gem/activestorage#lib/active_storage/service.rb:164
  def custom_metadata_headers(metadata); end

  # pkg:gem/activestorage#lib/active_storage/service.rb:168
  def instrument(operation, payload = T.unsafe(nil), &block); end

  # pkg:gem/activestorage#lib/active_storage/service.rb:156
  def private_url(key, expires_in:, filename:, disposition:, content_type:, **_arg5); end

  # pkg:gem/activestorage#lib/active_storage/service.rb:160
  def public_url(key, **_arg1); end

  # pkg:gem/activestorage#lib/active_storage/service.rb:174
  def service_name; end

  class << self
    # Override in subclasses that stitch together multiple services and hence
    # need to build additional services using the configurator.
    #
    # Passes the configurator and all of the service's config as keyword args.
    #
    # See MirrorService for an example.
    #
    # pkg:gem/activestorage#lib/active_storage/service.rb:62
    def build(configurator:, name:, service: T.unsafe(nil), **service_config); end

    # Configure an Active Storage service by name from a set of configurations,
    # typically loaded from a YAML file. The Active Storage engine uses this
    # to set the global Active Storage service when the app boots.
    #
    # pkg:gem/activestorage#lib/active_storage/service.rb:52
    def configure(service_name, configurations); end
  end
end

# pkg:gem/activestorage#lib/active_storage/service/configurator.rb:4
class ActiveStorage::Service::Configurator
  # pkg:gem/activestorage#lib/active_storage/service/configurator.rb:11
  def initialize(configurations); end

  # pkg:gem/activestorage#lib/active_storage/service/configurator.rb:15
  def build(service_name); end

  # pkg:gem/activestorage#lib/active_storage/service/configurator.rb:5
  def configurations; end

  # pkg:gem/activestorage#lib/active_storage/service/configurator.rb:22
  def inspect; end

  private

  # pkg:gem/activestorage#lib/active_storage/service/configurator.rb:29
  def config_for(name); end

  # pkg:gem/activestorage#lib/active_storage/service/configurator.rb:35
  def resolve(class_name); end

  class << self
    # pkg:gem/activestorage#lib/active_storage/service/configurator.rb:7
    def build(service_name, configurations); end
  end
end

# pkg:gem/activestorage#lib/active_storage/structured_event_subscriber.rb:6
class ActiveStorage::StructuredEventSubscriber < ::ActiveSupport::StructuredEventSubscriber
  # pkg:gem/activestorage#lib/active_storage/structured_event_subscriber.rb:29
  def preview(event); end

  # pkg:gem/activestorage#lib/active_storage/structured_event_subscriber.rb:36
  def service_delete(event); end

  # pkg:gem/activestorage#lib/active_storage/structured_event_subscriber.rb:43
  def service_delete_prefixed(event); end

  # pkg:gem/activestorage#lib/active_storage/structured_event_subscriber.rb:15
  def service_download(event); end

  # pkg:gem/activestorage#lib/active_storage/structured_event_subscriber.rb:50
  def service_exist(event); end

  # pkg:gem/activestorage#lib/active_storage/structured_event_subscriber.rb:68
  def service_mirror(event); end

  # pkg:gem/activestorage#lib/active_storage/structured_event_subscriber.rb:22
  def service_streaming_download(event); end

  # pkg:gem/activestorage#lib/active_storage/structured_event_subscriber.rb:7
  def service_upload(event); end

  # pkg:gem/activestorage#lib/active_storage/structured_event_subscriber.rb:59
  def service_url(event); end
end

# pkg:gem/activestorage#lib/active_storage.rb:381
module ActiveStorage::Transformers
  extend ::ActiveSupport::Autoload
end

# pkg:gem/activestorage#lib/active_storage/transformers/null_transformer.rb:5
class ActiveStorage::Transformers::NullTransformer < ::ActiveStorage::Transformers::Transformer
  private

  # pkg:gem/activestorage#lib/active_storage/transformers/null_transformer.rb:7
  def process(file, format:); end
end

# = Active Storage \Transformers \Transformer
#
# A Transformer applies a set of transformations to an image.
#
# The following concrete subclasses are included in Active Storage:
#
# * ActiveStorage::Transformers::ImageProcessingTransformer:
#   backed by ImageProcessing, a common interface for MiniMagick and ruby-vips
#
# pkg:gem/activestorage#lib/active_storage/transformers/transformer.rb:13
class ActiveStorage::Transformers::Transformer
  # pkg:gem/activestorage#lib/active_storage/transformers/transformer.rb:16
  def initialize(transformations); end

  # Applies the transformations to the source image in +file+, producing a target image in the
  # specified +format+. Yields an open Tempfile containing the target image. Closes and unlinks
  # the output tempfile after yielding to the given block. Returns the result of the block.
  #
  # pkg:gem/activestorage#lib/active_storage/transformers/transformer.rb:23
  def transform(file, format:); end

  # pkg:gem/activestorage#lib/active_storage/transformers/transformer.rb:14
  def transformations; end

  private

  # Returns an open Tempfile containing a transformed image in the given +format+.
  # All subclasses implement this method.
  #
  # pkg:gem/activestorage#lib/active_storage/transformers/transformer.rb:36
  def process(file, format:); end
end

# Raised when ActiveStorage::Blob#preview is called on a blob that isn't previewable.
# Use ActiveStorage::Blob#previewable? to determine whether a blob is previewable.
#
# pkg:gem/activestorage#lib/active_storage/errors.rb:13
class ActiveStorage::UnpreviewableError < ::ActiveStorage::Error; end

# Raised when ActiveStorage::Blob#representation is called on a blob that isn't representable.
# Use ActiveStorage::Blob#representable? to determine whether a blob is representable.
#
# pkg:gem/activestorage#lib/active_storage/errors.rb:17
class ActiveStorage::UnrepresentableError < ::ActiveStorage::Error; end

# pkg:gem/activestorage#lib/active_storage/gem_version.rb:9
module ActiveStorage::VERSION; end

# pkg:gem/activestorage#lib/active_storage/gem_version.rb:10
ActiveStorage::VERSION::MAJOR = T.let(T.unsafe(nil), Integer)

# pkg:gem/activestorage#lib/active_storage/gem_version.rb:11
ActiveStorage::VERSION::MINOR = T.let(T.unsafe(nil), Integer)

# pkg:gem/activestorage#lib/active_storage/gem_version.rb:13
ActiveStorage::VERSION::PRE = T.let(T.unsafe(nil), String)

# pkg:gem/activestorage#lib/active_storage/gem_version.rb:15
ActiveStorage::VERSION::STRING = T.let(T.unsafe(nil), String)

# pkg:gem/activestorage#lib/active_storage/gem_version.rb:12
ActiveStorage::VERSION::TINY = T.let(T.unsafe(nil), Integer)

# pkg:gem/activestorage#lib/active_storage/vips.rb:21
ActiveStorage::VIPS_AVAILABLE = T.let(T.unsafe(nil), FalseClass)
