# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bcp47_spec` gem.
# Please instead update this file by running `bin/tapioca gem bcp47_spec`.


# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca#manually-requiring-parts-of-a-gem
