# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `guard-compat` gem.
# Please instead update this file by running `bin/tapioca gem guard-compat`.


# NOTE: Do NOT require "guard/plugin" - it will either be already required, or
# a stub will be supplied by the test class
# Provided empty definition so requiring the plugin without Guard won't crash
# (e.g. when added to a Gemfile without `require: false`)
#
# pkg:gem/guard-compat#lib/guard/compat/plugin.rb:23
module Guard
  extend ::Guard::Internals::Helpers
end

# pkg:gem/guard-compat#lib/guard/compat/plugin.rb:24
module Guard::Compat
  class << self
    # TODO: this is just a temporary workaround to allow plugins
    # to use watcher patterns in run_all
    #
    # pkg:gem/guard-compat#lib/guard/compat/plugin.rb:27
    def matching_files(plugin, files); end

    # pkg:gem/guard-compat#lib/guard/compat/plugin.rb:39
    def watched_directories; end
  end
end

# pkg:gem/guard-compat#lib/guard/compat/plugin.rb:54
module Guard::Compat::UI
  class << self
    # pkg:gem/guard-compat#lib/guard/compat/plugin.rb:55
    def color(text, *colors); end

    # pkg:gem/guard-compat#lib/guard/compat/plugin.rb:63
    def color_enabled?; end

    # pkg:gem/guard-compat#lib/guard/compat/plugin.rb:95
    def debug(message, options = T.unsafe(nil)); end

    # pkg:gem/guard-compat#lib/guard/compat/plugin.rb:103
    def deprecation(message, options = T.unsafe(nil)); end

    # pkg:gem/guard-compat#lib/guard/compat/plugin.rb:87
    def error(message, options = T.unsafe(nil)); end

    # pkg:gem/guard-compat#lib/guard/compat/plugin.rb:71
    def info(message, options = T.unsafe(nil)); end

    # pkg:gem/guard-compat#lib/guard/compat/plugin.rb:111
    def notify(msg, options = T.unsafe(nil)); end

    # pkg:gem/guard-compat#lib/guard/compat/plugin.rb:79
    def warning(message, options = T.unsafe(nil)); end
  end
end
