# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `nenv` gem.
# Please instead update this file by running `bin/tapioca gem nenv`.


# pkg:gem/nenv#lib/nenv/version.rb:1
module Nenv
  class << self
    # pkg:gem/nenv#lib/nenv.rb:26
    def instance; end

    # pkg:gem/nenv#lib/nenv.rb:18
    def method_missing(meth, *args); end

    # pkg:gem/nenv#lib/nenv.rb:22
    def reset; end

    # pkg:gem/nenv#lib/nenv.rb:14
    def respond_to?(meth); end
  end
end

# pkg:gem/nenv#lib/nenv/autoenvironment.rb:3
class Nenv::AutoEnvironment < ::Nenv::Environment
  # pkg:gem/nenv#lib/nenv/autoenvironment.rb:4
  def method_missing(meth, *args); end
end

# pkg:gem/nenv#lib/nenv/builder.rb:4
module Nenv::Builder
  class << self
    # pkg:gem/nenv#lib/nenv/builder.rb:5
    def build(&block); end
  end
end

# pkg:gem/nenv#lib/nenv/environment/dumper.rb:2
class Nenv::Environment
  # pkg:gem/nenv#lib/nenv/environment.rb:21
  def initialize(namespace = T.unsafe(nil)); end

  # pkg:gem/nenv#lib/nenv/environment.rb:25
  def create_method(meth, &block); end

  private

  # pkg:gem/nenv#lib/nenv/environment.rb:35
  def _namespaced_sanitize(meth); end

  # pkg:gem/nenv#lib/nenv/environment.rb:31
  def _sanitize(meth); end

  class << self
    # pkg:gem/nenv#lib/nenv/environment.rb:44
    def _create_env_accessor(klass, meth, &block); end

    # pkg:gem/nenv#lib/nenv/environment.rb:40
    def create_method(meth, &block); end

    private

    # pkg:gem/nenv#lib/nenv/environment.rb:66
    def _create_env_reader(klass, meth, &block); end

    # pkg:gem/nenv#lib/nenv/environment.rb:56
    def _create_env_writer(klass, meth, &block); end

    # pkg:gem/nenv#lib/nenv/environment.rb:76
    def _fail_if_accessor_exists(klass, meth); end
  end
end

# pkg:gem/nenv#lib/nenv/environment.rb:15
class Nenv::Environment::AlreadyExistsError < ::Nenv::Environment::MethodError
  # pkg:gem/nenv#lib/nenv/environment.rb:16
  def message; end
end

# pkg:gem/nenv#lib/nenv/environment/dumper.rb:3
module Nenv::Environment::Dumper
  class << self
    # pkg:gem/nenv#lib/nenv/environment/dumper.rb:6
    def setup(&callback); end
  end
end

# pkg:gem/nenv#lib/nenv/environment/dumper/default.rb:3
module Nenv::Environment::Dumper::Default
  class << self
    # pkg:gem/nenv#lib/nenv/environment/dumper/default.rb:4
    def call(raw_value); end
  end
end

# pkg:gem/nenv#lib/nenv/environment.rb:6
class Nenv::Environment::Error < ::ArgumentError; end

# pkg:gem/nenv#lib/nenv/environment/loader.rb:3
module Nenv::Environment::Loader
  class << self
    # pkg:gem/nenv#lib/nenv/environment/loader.rb:7
    def setup(meth, &callback); end
  end
end

# pkg:gem/nenv#lib/nenv/environment/loader/default.rb:3
module Nenv::Environment::Loader::Default
  class << self
    # pkg:gem/nenv#lib/nenv/environment/loader/default.rb:4
    def call(raw_value); end
  end
end

# pkg:gem/nenv#lib/nenv/environment/loader/predicate.rb:3
module Nenv::Environment::Loader::Predicate
  class << self
    # pkg:gem/nenv#lib/nenv/environment/loader/predicate.rb:4
    def call(raw_value); end
  end
end

# pkg:gem/nenv#lib/nenv/environment.rb:9
class Nenv::Environment::MethodError < ::Nenv::Environment::Error
  # pkg:gem/nenv#lib/nenv/environment.rb:10
  def initialize(meth); end
end

# pkg:gem/nenv#lib/nenv/version.rb:2
Nenv::VERSION = T.let(T.unsafe(nil), String)

class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin

  private

  # pkg:gem/nenv#lib/nenv.rb:6
  def Nenv(namespace = T.unsafe(nil)); end
end
