# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-rbs_inline` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-rbs_inline`.


# pkg:gem/rubocop-rbs_inline#lib/rubocop/rbs_inline/version.rb:3
module RuboCop; end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/ast_utils.rb:4
module RuboCop::Cop; end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/ast_utils.rb:5
module RuboCop::Cop::Style; end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/ast_utils.rb:6
module RuboCop::Cop::Style::RbsInline; end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/ast_utils.rb:7
module RuboCop::Cop::Style::RbsInline::ASTUtils
  # @rbs node: RuboCop::AST::Node
  # @rbs default: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/ast_utils.rb:10
  def end_line(node, default:); end

  # @rbs node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/ast_utils.rb:16
  def name_location(node); end

  # @rbs node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/ast_utils.rb:22
  def source!(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/ast_utils.rb:29
  def value_to_sym(node); end
end

# Utility module for parsing RBS inline comments
# @rbs module-self RuboCop::Cop::Base
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/comment_parser.rb:13
module RuboCop::Cop::Style::RbsInline::CommentParser
  # Find @rbs parameter annotations before a method definition
  # @rbs def_line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/comment_parser.rb:84
  def find_doc_style_param_annotations(def_line); end

  # Find @rbs return annotation before a method definition
  # @rbs def_line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/comment_parser.rb:102
  def find_doc_style_return_annotation(def_line); end

  # Find the last comment in a consecutive block starting from start_comment
  # @rbs start_comment: Parser::Source::Comment
  # @rbs &block: (Parser::Source::Comment) -> bool
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/comment_parser.rb:25
  def find_last_consecutive_comment(start_comment, &block); end

  # Find the leading annotation comment before the given line
  # @rbs def_line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/comment_parser.rb:45
  def find_leading_annotation(def_line); end

  # Find method type signature comments (#:) before a method definition
  # @rbs def_line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/comment_parser.rb:58
  def find_method_type_signature_comments(def_line); end

  # Find trailing comment on the same line as the method definition
  # @rbs line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/comment_parser.rb:75
  def find_trailing_comment(line); end

  # Returns true if there are 2 or more leading #: method type signature lines (overloads).
  # Overloads cannot be expressed in doc_style format, so they take precedence over style config.
  # @rbs def_line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/comment_parser.rb:116
  def overload_type_signatures?(def_line); end

  # Parse comments from the source code
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/comment_parser.rb:17
  def parse_comments; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/comment_parser.rb:14
  def parsed_comments; end
end

# Checks that `#:` inline type annotations in `Data.define` blocks are aligned.
#
# Each `#:` annotation comment should start at the same column, determined by
# the longest attribute name (plus trailing comma). Folded `Data.define` calls
# (where attributes are not one per line) are excluded.
#
# @example
#   # bad
#   MethodEntry = Data.define(
#     :name, #: Symbol
#     :node,       #: Parser::AST::Node
#     :visibility  #: Symbol
#   )
#
#   # good
#   MethodEntry = Data.define(
#     :name,       #: Symbol
#     :node,       #: Parser::AST::Node
#     :visibility  #: Symbol
#   )
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_class_comment_alignment.rb:28
class RuboCop::Cop::Style::RbsInline::DataClassCommentAlignment < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Style::RbsInline::ASTUtils
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Style::RbsInline::SourceCodeHelper
  extend ::RuboCop::Cop::AutoCorrector

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_class_comment_alignment.rb:37
  def on_send(node); end

  private

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_class_comment_alignment.rb:103
  def annotation_column(node); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_class_comment_alignment.rb:78
  def check_annotation_alignment(node); end

  # @rbs corrector: RuboCop::Cop::Corrector
  # @rbs arg: RuboCop::AST::Node
  # @rbs comment: Parser::Source::Comment
  # @rbs expected_col: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_class_comment_alignment.rb:117
  def correct_alignment(corrector, arg, comment, expected_col); end

  # @rbs arg: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_class_comment_alignment.rb:59
  def data_attribute?(arg); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_class_comment_alignment.rb:64
  def data_attributes(node); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_class_comment_alignment.rb:47
  def data_define?(node); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_class_comment_alignment.rb:69
  def folded_data_class?(node); end

  # @rbs line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_class_comment_alignment.rb:97
  def inline_type_comment(line); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_class_comment_alignment.rb:34
RuboCop::Cop::Style::RbsInline::DataClassCommentAlignment::MSG = T.let(T.unsafe(nil), String)

# Checks for `Data.define` calls with a block.
#
# RBS::Inline does not parse the contents of `Data.define` blocks, so any
# methods defined inside will not be recognized for type checking. Instead,
# call `Data.define` without a block and define additional methods by
# reopening the class separately.
#
# NOTE: This is a known limitation of RBS::Inline. See
# https://github.com/soutaro/rbs-inline/pull/183 for the upstream fix.
#
# @example
#   # bad
#   User = Data.define(:name, :role) do
#     def admin? = role == :admin #: bool
#   end
#
#   # good
#   User = Data.define(:name, :role)
#
#   class User
#     def admin? = role == :admin #: bool
#   end
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_define_with_block.rb:30
class RuboCop::Cop::Style::RbsInline::DataDefineWithBlock < ::RuboCop::Cop::Base
  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_define_with_block.rb:36
  def on_send(node); end

  private

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_define_with_block.rb:48
  def data_define?(node); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/data_define_with_block.rb:31
RuboCop::Cop::Style::RbsInline::DataDefineWithBlock::MSG = T.let(T.unsafe(nil), String)

# Checks that `@rbs!` comments (embedded RBS) are followed by a blank line.
#
# RBS::Inline requires `@rbs!` comments to be standalone comments,
# meaning they should not have any code immediately following them.
# A blank line after the `@rbs!` block ensures proper separation.
#
# @example
#   # bad
#   # @rbs! type foo = Integer
#   def method
#   end
#
#   # good
#   # @rbs! type foo = Integer
#
#   def method
#   end
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/embedded_rbs_spacing.rb:28
class RuboCop::Cop::Style::RbsInline::EmbeddedRbsSpacing < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Style::RbsInline::SourceCodeHelper
  include ::RuboCop::Cop::Style::RbsInline::CommentParser
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/embedded_rbs_spacing.rb:35
  def on_new_investigation; end

  private

  # @rbs line_number: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/embedded_rbs_spacing.rb:65
  def block_end_line?(line_number); end

  # @rbs annotation: RBS::Inline::AST::Annotations::Embedded
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/embedded_rbs_spacing.rb:52
  def check_embedded_annotation(annotation); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/embedded_rbs_spacing.rb:41
  def check_embedded_rbs_spacing; end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/embedded_rbs_spacing.rb:33
RuboCop::Cop::Style::RbsInline::EmbeddedRbsSpacing::MSG = T.let(T.unsafe(nil), String)

# IRB::Inline expects annotations comments to start with `#:` or `# @rbs`.
# This cop checks for comments that do not match the expected pattern.
#
# @example
#   # bad
#   # () -> void
#   # : () -> void
#   # rbs param: String
#
#   # good
#   #: () -> void
#   # @rbs param: String
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:22
class RuboCop::Cop::Style::RbsInline::InvalidComment < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:38
  def on_new_investigation; end

  private

  # @rbs comment: Parser::Source::Comment
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:47
  def check_comment(comment); end

  # @rbs comments: Array[Parser::Source::Comment]
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:67
  def consume_embedded_rbs(comments); end

  # @rbs text: String
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:57
  def corrected_text(text); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:36
RuboCop::Cop::Style::RbsInline::InvalidComment::MISSING_AT_SIGN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:33
RuboCop::Cop::Style::RbsInline::InvalidComment::MISSING_HASH_COLON = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:35
RuboCop::Cop::Style::RbsInline::InvalidComment::MIXED_ANNOTATION = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:25
RuboCop::Cop::Style::RbsInline::InvalidComment::MSG = T.let(T.unsafe(nil), String)

# refs: https://github.com/soutaro/rbs-inline/blob/main/lib/rbs/inline/annotation_parser/tokenizer.rb
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:28
RuboCop::Cop::Style::RbsInline::InvalidComment::RBS_INLINE_KEYWORDS = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:29
RuboCop::Cop::Style::RbsInline::InvalidComment::RBS_INLINE_KEYWORD_PATTERN = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:31
RuboCop::Cop::Style::RbsInline::InvalidComment::SIGNATURE_PATTERN = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_comment.rb:34
RuboCop::Cop::Style::RbsInline::InvalidComment::SPACE_BEFORE_COLON = T.let(T.unsafe(nil), Regexp)

# IRB::Inline expects the types of annotation comments are valid syntax.
# This cop checks for comments that do not match the expected pattern.
#
# @example
#   # bad
#   # @rbs arg: Hash[Symbol,
#   # @rbs &block: String
#   def method(arg); end
#
#   # good
#   # @rbs arg: Hash[Symbol, String]
#   # @rbs &block: () -> void
#   def method(arg); end
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_types.rb:23
class RuboCop::Cop::Style::RbsInline::InvalidTypes < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Style::RbsInline::CommentParser
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Style::RbsInline::SourceCodeHelper
  include ::RBS::Inline::AST::Annotations
  include ::RBS::Inline::AST::Members

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_types.rb:32
  def on_new_investigation; end

  private

  # @rbs annotation: RBS::Inline::AST::Annotations::t
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_types.rb:46
  def invalid_annotation?(annotation); end

  # @rbs annotation: RBS::Inline::AST::Annotations::Embedded
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_types.rb:59
  def invalid_embedded?(annotation); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/invalid_types.rb:30
RuboCop::Cop::Style::RbsInline::InvalidTypes::MSG = T.let(T.unsafe(nil), String)

# IRB::Inline expects annotations comments for keywords are not separeted with `:`.
# This cop checks for comments that do not match the expected pattern.
#
# @example
#   # bad
#   # @rbs module-self: String
#
#   # good
#   # @rbs module-self String
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/keyword_separator.rb:17
class RuboCop::Cop::Style::RbsInline::KeywordSeparator < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Style::RbsInline::CommentParser
  include ::RuboCop::Cop::RangeHelp
  extend ::RuboCop::Cop::AutoCorrector

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/keyword_separator.rb:41
  def on_def(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/keyword_separator.rb:46
  def on_defs(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/keyword_separator.rb:50
  def on_investigation_end; end

  # @rbs @method_annotation_lines: Set[Integer]
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/keyword_separator.rb:34
  def on_new_investigation; end

  private

  # Collect line numbers of leading annotation comments for a method definition
  # into @method_annotation_lines.
  # @rbs def_line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/keyword_separator.rb:69
  def collect_method_annotation_comments(def_line); end

  # @rbs comment: Parser::Source::Comment
  # @rbs matched: MatchData
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/keyword_separator.rb:94
  def invalid_location_for(comment, matched); end

  # Returns true when `comment` is a no-argument keyword (`override` or `skip`)
  # followed by `:` but no type.
  # @rbs comment: Parser::Source::Comment
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/keyword_separator.rb:88
  def no_argument_keyword_without_type?(comment); end

  # Returns true when comment is a leading annotation for a method definition and
  # is not a no-argument keyword (`override` or `skip`) followed by `:` without a type.
  # @rbs comment: Parser::Source::Comment
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/keyword_separator.rb:79
  def valid_method_annotation?(comment); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/keyword_separator.rb:22
RuboCop::Cop::Style::RbsInline::KeywordSeparator::MSG = T.let(T.unsafe(nil), String)

# `override` and `skip` are standalone markers that take no arguments.
# Even before a method definition they may not be followed by `:` alone,
# because `# @rbs override:` (no type) is not a valid parameter annotation.
# Only `# @rbs override: SomeType` (with a type) is valid as a parameter annotation.
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/keyword_separator.rb:30
RuboCop::Cop::Style::RbsInline::KeywordSeparator::NO_ARGUMENT_KEYWORDS = T.let(T.unsafe(nil), Array)

# refs: https://github.com/soutaro/rbs-inline/blob/main/lib/rbs/inline/annotation_parser/tokenizer.rb
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/keyword_separator.rb:25
RuboCop::Cop::Style::RbsInline::KeywordSeparator::RBS_INLINE_KEYWORDS = T.let(T.unsafe(nil), Array)

# Checks that method-related `@rbs` annotations are placed immediately before method definitions.
#
# Method-related annotations (`@rbs param`, `@rbs return`, `@rbs &block`, `@rbs override`,
# `@rbs skip`, `@rbs %a{...}`, `# @rbs (...) -> Type`, `#: (...) -> Type`) must be placed
# directly before the method definition they describe, without any blank lines in between.
# These annotations should not appear in standalone locations without an immediately following
# method definition.
#
# @example
#   # bad
#   # @rbs param x: Integer
#   # @rbs return: String
#
#   def method(x)
#   end
#
#   # bad
#   #: (Integer) -> String
#
#   def method(x)
#   end
#
#   # bad
#   # @rbs param x: Integer
#   # @rbs return: String
#   puts "something"
#
#   # good
#   # @rbs param x: Integer
#   # @rbs return: String
#   def method(x)
#   end
#
#   # good
#   #: (Integer) -> String
#   def method(x)
#   end
#
#   # good
#   # @rbs x: Integer
#   private_class_method def self.method(x)
#   end
#
#   # good
#   # @rbs x: Integer
#   private def method(x)
#   end
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:58
class RuboCop::Cop::Style::RbsInline::MethodCommentSpacing < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Style::RbsInline::SourceCodeHelper
  include ::RuboCop::Cop::Style::RbsInline::CommentParser
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:71
  def on_new_investigation; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:69
  def processed_comments; end

  private

  # @rbs comment: Prism::Comment
  # @rbs blank_line_number: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:148
  def check_blank_line_case(comment, blank_line_number); end

  # @rbs comment: RBS::Inline::AnnotationParser::ParsingResult
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:101
  def check_method_annotation(comment); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:79
  def check_method_comment_spacing; end

  # @rbs comment: RBS::Inline::AnnotationParser::ParsingResult
  # @rbs next_line_number: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:135
  def check_spacing_after_annotation(comment, next_line_number); end

  # @rbs line_number: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:174
  def method_definition_line?(line_number); end

  # @rbs comment: RBS::Inline::AnnotationParser::ParsingResult
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:112
  def method_related_annotation?(comment); end

  # @rbs blank_line_number: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:159
  def register_blank_line_offense(blank_line_number); end

  # @rbs comment: RBS::Inline::AnnotationParser::ParsingResult
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:167
  def skip_only_annotation?(comment); end

  # Check if this is a trailing comment after Ruby code on the same line
  # @rbs comment: RBS::Inline::AnnotationParser::ParsingResult
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:90
  def trailing_comment?(comment); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:66
RuboCop::Cop::Style::RbsInline::MethodCommentSpacing::METHOD_DEFINITION_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:64
RuboCop::Cop::Style::RbsInline::MethodCommentSpacing::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/method_comment_spacing.rb:65
RuboCop::Cop::Style::RbsInline::MethodCommentSpacing::MSG_WITH_BLANK_LINE = T.let(T.unsafe(nil), String)

# Checks that `Data.define` attributes have inline type annotations.
#
# Each attribute passed to `Data.define` should have a trailing `#:` type
# annotation comment on the same line.
#
# @example
#   # bad
#   MethodEntry = Data.define(:name, :node, :visibility)
#
#   # good
#   MethodEntry = Data.define(
#     :name,       #: Symbol
#     :node,       #: Parser::AST::Node
#     :visibility  #: Symbol
#   )
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:23
class RuboCop::Cop::Style::RbsInline::MissingDataClassAnnotation < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Style::RbsInline::ASTUtils
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Style::RbsInline::SourceCodeHelper
  extend ::RuboCop::Cop::AutoCorrector

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:32
  def on_send(node); end

  private

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:82
  def add_offenses_for_folded_data_class(node); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:159
  def annotation_column(node); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:106
  def build_multiline_replacement(node); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:122
  def check_multiline_data_class(node); end

  # @rbs corrector: RuboCop::Cop::Corrector
  # @rbs node: RuboCop::AST::SendNode
  # @rbs arg: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:133
  def correct_multiline(corrector, node, arg); end

  # @rbs arg: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:57
  def data_attribute?(arg); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:62
  def data_attributes(node); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:45
  def data_define?(node); end

  # @rbs line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:170
  def find_regular_comment(line); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:73
  def folded_data_class?(node); end

  # @rbs line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:67
  def inline_type_annotation?(line); end

  # @rbs corrector: RuboCop::Cop::Corrector
  # @rbs node: RuboCop::AST::SendNode
  # @rbs arg: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:147
  def insert_annotation(corrector, node, arg); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:99
  def longest_argname(node); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_data_class_annotation.rb:29
RuboCop::Cop::Style::RbsInline::MissingDataClassAnnotation::MSG = T.let(T.unsafe(nil), String)

# Checks that method definitions and `attr_*` declarations have
# RBS inline type annotations.
#
# The `EnforcedStyle` option determines which annotation format is required:
#
# - `doc_style`: Requires `# @rbs` annotations
# - `doc_style_and_return_annotation`: Requires `# @rbs` parameters and trailing `#:` return type
# - `method_type_signature`: Requires `#:` annotation comments only
# - `method_type_signature_or_return_annotation`: Requires `#:` annotation for methods with arguments;
#   accepts either `#:` annotation or trailing `#:` return type for methods without arguments
#
# The `Visibility` option determines which methods to check:
#
# - `all`: Checks all methods regardless of visibility (default)
# - `public`: Only checks public methods and `attr_*` declarations
#
# Methods annotated with `# @rbs skip` are always excluded from inspection.
#
# @example EnforcedStyle: doc_style
#   # bad
#   def greet(name)
#     "Hello, #{name}"
#   end
#
#   # bad
#   attr_reader :name
#
#   # good
#   # @rbs name: String
#   # @rbs return: String
#   def greet(name)
#     "Hello, #{name}"
#   end
#
#   # good
#   # @rbs name: String
#   attr_reader :name
#
# @example EnforcedStyle: doc_style_and_return_annotation
#   # bad - no annotation
#   def greet(name)
#     "Hello, #{name}"
#   end
#
#   # bad - missing trailing return type
#   # @rbs name: String
#   def greet(name)
#     "Hello, #{name}"
#   end
#
#   # good - @rbs parameters + trailing return type
#   # @rbs name: String
#   def greet(name) #: String
#     "Hello, #{name}"
#   end
#
#   # good - attr with trailing type
#   attr_reader :name #: String
#
# @example EnforcedStyle: method_type_signature
#   # bad
#   def greet(name)
#     "Hello, #{name}"
#   end
#
#   # bad
#   attr_reader :name
#
#   # good
#   #: (String) -> String
#   def greet(name)
#     "Hello, #{name}"
#   end
#
#   # good
#   #: String
#   attr_reader :name
#
# @example EnforcedStyle: method_type_signature_or_return_annotation
#   # bad - method with arguments requires method_type_signature
#   def greet(name)
#     "Hello, #{name}"
#   end
#
#   # bad - inline trailing comment is not accepted for methods with arguments
#   def greet(name) #: String
#     "Hello, #{name}"
#   end
#
#   # good - method_type_signature for methods with arguments
#   #: (String) -> String
#   def greet(name)
#     "Hello, #{name}"
#   end
#
#   # good - method_type_signature for methods without arguments
#   #: -> String
#   def greet
#     "Hello"
#   end
#
#   # good - trailing return type annotation for methods without arguments
#   def greet #: String
#     "Hello"
#   end
#
#   # good - attr with trailing type
#   attr_reader :name #: String
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:118
class RuboCop::Cop::Style::RbsInline::MissingTypeAnnotation < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Style::RbsInline::ASTUtils
  include ::RuboCop::Cop::Style::RbsInline::CommentParser
  include ::RuboCop::Cop::ConfigurableEnforcedStyle
  include ::RuboCop::Cop::RangeHelp

  # @rbs _node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:168
  def after_class(_node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:174
  def after_module(_node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:175
  def after_sclass(_node); end

  # @rbs _node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:159
  def on_class(_node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:178
  def on_def(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:184
  def on_defs(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:153
  def on_investigation_end; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:164
  def on_module(_node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:146
  def on_new_investigation; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:165
  def on_sclass(_node); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:187
  def on_send(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:144
  def unannotated_methods_stack; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:143
  def visibility_stack; end

  private

  # @rbs line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:371
  def annotated_attribute_method?(line); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:358
  def args_node_for(node); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:344
  def check_attribute_method(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:260
  def check_def(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:246
  def check_method_entries; end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:308
  def check_method_parameters_in_doc_style(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:282
  def check_method_type_signature(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:299
  def check_method_type_signature_or_return_annotation(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:290
  def check_method_type_signature_or_return_annotation_style(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:330
  def check_return_type_in_doc_style(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:337
  def check_return_type_in_return_annotation(node); end

  # Returns the method entries for the current scope (class/module)
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:201
  def current_method_entries; end

  # @rbs node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:227
  def current_visibility(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:377
  def doc_style_annotation_name(annotation); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:366
  def method_has_arguments?(node); end

  # Returns the last line of the method parameter list (the closing ) line, or the def line if no parens).
  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:352
  def method_parameter_list_end_line(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:431
  def offense_range_for_def(node); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:219
  def on_attribute_method(node); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:206
  def on_visibility_modifier(node); end

  # Returns acceptable annotation name variants for the parameter, or nil for unrecognized types.
  # @rbs argument: RuboCop::AST::Node
  # @rbs name: String
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:409
  def param_candidate_names(argument, name); end

  # Returns the display name for a parameter node, used in offense messages.
  # @rbs argument: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:420
  def param_display_name(argument); end

  # @rbs line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:399
  def rbs_method_type_annotation?(line); end

  # @rbs line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:391
  def skip_annotation?(line); end

  # @rbs visibility: visibility
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:240
  def target_node?(visibility); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:130
RuboCop::Cop::Style::RbsInline::MissingTypeAnnotation::ATTRIBUTE_METHOD_MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:132
RuboCop::Cop::Style::RbsInline::MissingTypeAnnotation::ATTR_METHODS = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:127
RuboCop::Cop::Style::RbsInline::MissingTypeAnnotation::DOC_STYLE_PARAM_MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:128
RuboCop::Cop::Style::RbsInline::MissingTypeAnnotation::DOC_STYLE_RETURN_MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:129
RuboCop::Cop::Style::RbsInline::MissingTypeAnnotation::DOC_STYLE_TRAILING_RETURN_MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:124
RuboCop::Cop::Style::RbsInline::MissingTypeAnnotation::METHOD_TYPE_SIGNATURE_MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:125
RuboCop::Cop::Style::RbsInline::MissingTypeAnnotation::METHOD_TYPE_SIGNATURE_OR_RETURN_ANNOTATION_MESSAGE = T.let(T.unsafe(nil), String)

# @rbs! type visibility = :public | :protected | :private
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:137
class RuboCop::Cop::Style::RbsInline::MissingTypeAnnotation::MethodEntry < ::Data
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:137
  def name; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:137
  def node; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:137
  def visibility; end

  class << self
    # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:137
    def [](*_arg0); end

    # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:137
    def inspect; end

    # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:137
    def members; end

    # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:137
    def new(*_arg0); end
  end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/missing_type_annotation.rb:133
RuboCop::Cop::Style::RbsInline::MissingTypeAnnotation::VISIBILITY_MODIFIERS = T.let(T.unsafe(nil), Array)

# IRB::Inline expects annotations comments for parameters are separated with `:`or allows annotation comments.
# This cop checks for comments that do not match the expected pattern.
#
# @example
#   # bad
#   # @rbs param String
#
#   # bad
#   # @rbs :param String
#
#   # good
#   # @rbs param: String
#
#   # good
#   # @rbs %a{pure}
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/parameters_separator.rb:22
class RuboCop::Cop::Style::RbsInline::ParametersSeparator < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/parameters_separator.rb:32
  def on_new_investigation; end

  private

  # @rbs keyword: String
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/parameters_separator.rb:80
  def corrected_keyword(keyword); end

  # @rbs comment: Parser::Source::Comment
  # @rbs matched: MatchData
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/parameters_separator.rb:62
  def invalid_location_for(comment, matched); end

  # @rbs comment: Parser::Source::Comment
  # @rbs matched: MatchData
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/parameters_separator.rb:70
  def keyword_range(comment, matched); end

  # @rbs matched: String?
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/parameters_separator.rb:49
  def valid_rbs_inline_comment?(matched); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/parameters_separator.rb:26
RuboCop::Cop::Style::RbsInline::ParametersSeparator::MSG = T.let(T.unsafe(nil), String)

# refs: https://github.com/soutaro/rbs-inline/blob/main/lib/rbs/inline/annotation_parser/tokenizer.rb
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/parameters_separator.rb:29
RuboCop::Cop::Style::RbsInline::ParametersSeparator::RBS_INLINE_KEYWORDS = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/parameters_separator.rb:30
RuboCop::Cop::Style::RbsInline::ParametersSeparator::RBS_INLINE_REGEXP_KEYWORDS = T.let(T.unsafe(nil), Array)

# Checks for redundant type annotations when `@rbs skip` or `@rbs override` is present.
#
# `@rbs skip` tells RBS::Inline to skip RBS generation for this method entirely.
# `@rbs override` tells RBS::Inline to inherit the type signature from the parent class.
# In both cases, any additional type annotations (method type signatures, parameter
# annotations, return type annotations) are redundant and will be ignored by RBS::Inline.
#
# @safety
#   Autocorrection is unsafe because it removes type annotations that may contain
#   useful documentation even if not used for RBS generation.
#
# @example
#   # bad - redundant method type signature with @rbs skip
#   # @rbs skip
#   #: (Integer) -> void
#   def method(a)
#   end
#
#   # bad - redundant doc-style method type annotation with @rbs skip
#   # @rbs skip
#   # @rbs (Integer) -> void
#   def method(a)
#   end
#
#   # bad - redundant param annotation with @rbs skip
#   # @rbs skip
#   # @rbs a: Integer
#   def method(a)
#   end
#
#   # bad - redundant trailing return type with @rbs skip
#   # @rbs skip
#   def method(a) #: void
#   end
#
#   # bad - redundant type annotations with @rbs override
#   # @rbs override
#   # @rbs a: Integer
#   def method(a)
#   end
#
#   # good
#   # @rbs skip
#   def method(a)
#   end
#
#   # good
#   # @rbs override
#   def method(a)
#   end
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:60
class RuboCop::Cop::Style::RbsInline::RedundantAnnotationWithSkip < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Style::RbsInline::CommentParser
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Style::RbsInline::SourceCodeHelper
  extend ::RuboCop::Cop::AutoCorrector

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:82
  def on_def(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:86
  def on_defs(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:76
  def on_new_investigation; end

  private

  # @rbs def_line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:147
  def check_doc_style_annotations(def_line); end

  # @rbs def_line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:115
  def check_skip_override(def_line); end

  # @rbs param_list_end_line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:176
  def check_trailing_return(param_list_end_line); end

  # @rbs annotation: untyped
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:163
  def doc_style_annotation_message(annotation); end

  # Returns the last line of the method parameter list (the closing ) line, or the def line if no parens).
  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:188
  def method_parameter_list_end_line(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:91
  def process(node); end

  # @rbs line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:101
  def skip_or_override_annotation?(line); end

  # @rbs first: RBS::Inline::AST::Annotations::Skip | RBS::Inline::AST::Annotations::Override
  # @rbs current: RBS::Inline::AST::Annotations::Skip | RBS::Inline::AST::Annotations::Override
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:138
  def skip_override_message(first, current); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:74
RuboCop::Cop::Style::RbsInline::RedundantAnnotationWithSkip::MSG_CONFLICTING_SKIP_OVERRIDE = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:68
RuboCop::Cop::Style::RbsInline::RedundantAnnotationWithSkip::MSG_DOC_STYLE_ANNOTATION = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:73
RuboCop::Cop::Style::RbsInline::RedundantAnnotationWithSkip::MSG_DUPLICATE_OVERRIDE = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:72
RuboCop::Cop::Style::RbsInline::RedundantAnnotationWithSkip::MSG_DUPLICATE_SKIP = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:66
RuboCop::Cop::Style::RbsInline::RedundantAnnotationWithSkip::MSG_METHOD_TYPE_SIGNATURE = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_annotation_with_skip.rb:70
RuboCop::Cop::Style::RbsInline::RedundantAnnotationWithSkip::MSG_TRAILING_RETURN = T.let(T.unsafe(nil), String)

# Checks for redundant `@rbs` instance variable type annotation when
# `attr_*` with an inline type annotation is already defined.
#
# When `attr_reader :foo #: Integer` is defined, a separate `# @rbs @foo: Integer`
# declaration for the instance variable is redundant. RBS::Inline automatically
# generates the instance variable type from the inline annotation on `attr_*`.
#
# @example
#   # bad
#   # @rbs @foo: Integer
#
#   attr_reader :foo #: Integer
#
#   # good
#   attr_reader :foo #: Integer
#
#   # good - no inline annotation, so ivar annotation is not redundant
#   # @rbs @foo: Integer
#
#   attr_reader :foo
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:30
class RuboCop::Cop::Style::RbsInline::RedundantInstanceVariableAnnotation < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Style::RbsInline::ASTUtils
  include ::RuboCop::Cop::Style::RbsInline::CommentParser
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Style::RbsInline::SourceCodeHelper
  extend ::RuboCop::Cop::AutoCorrector

  # @rbs node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:65
  def after_class(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:72
  def after_module(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:40
  def attributes_scope_stack; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:41
  def ivar_annotations; end

  # @rbs _node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:58
  def on_class(_node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:51
  def on_investigation_end; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:62
  def on_module(_node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:43
  def on_new_investigation; end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:75
  def on_send(node); end

  private

  # @rbs annotation: RBS::Inline::AST::Annotations::IvarType
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:141
  def add_ivar_offense(annotation); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:151
  def attribute_names_from(node); end

  # @rbs start_line: Integer
  # @rbs end_line: Integer | Float
  # @rbs attributes: Set[Symbol]
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:134
  def check_offenses(start_line, end_line, attributes); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:96
  def collect_ivar_annotations; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:92
  def current_attributes_scope; end

  # @rbs start_line: Integer
  # @rbs end_line: Integer | Float
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:111
  def extract_ivar_annotations(start_line, end_line); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:88
  def pop_attributes_scope; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:84
  def push_attributes_scope; end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:123
  def register_attribute_method(node); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:38
RuboCop::Cop::Style::RbsInline::RedundantInstanceVariableAnnotation::ATTRIBUTE_METHODS = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_instance_variable_annotation.rb:37
RuboCop::Cop::Style::RbsInline::RedundantInstanceVariableAnnotation::MSG = T.let(T.unsafe(nil), String)

# Checks for redundant type annotations when multiple type specifications
# exist for the same method definition.
#
# Supports three styles that align with `MissingTypeAnnotation`:
# - `method_type_signature`: Prefers `#:` annotation comments with full method signature
# - `doc_style`: Prefers `# @rbs` annotations for both parameters and return types
# - `doc_style_and_return_annotation`: Prefers `# @rbs` params with trailing `#:` return type
#
# @safety
#   Autocorrection is unsafe because it removes redundant annotations even when
#   the preferred style annotation is not present. In such cases, the autocorrection
#   will remove type information, and `MissingTypeAnnotation` will report the missing
#   annotation that should be added in the preferred style
#
# @example EnforcedStyle: method_type_signature
#   # bad - redundant @rbs parameter annotations
#   # @rbs a: Integer
#   #: (Integer) -> void
#   def method(a)
#   end
#
#   # bad - redundant trailing return type
#   #: () -> String
#   def method(arg) #: String
#   end
#
#   # bad - redundant @rbs return annotation
#   # @rbs return: String
#   #: () -> String
#   def method(arg)
#   end
#
#   # good
#   #: (Integer) -> String
#   def method(a)
#   end
#
# @example EnforcedStyle: doc_style
#   # bad - redundant annotation comment with parameters
#   # @rbs a: Integer
#   #: (Integer) -> void
#   def method(a)
#   end
#
#   # bad - redundant trailing return type
#   # @rbs return: String
#   def method(arg) #: String
#   end
#
#   # good
#   # @rbs a: Integer
#   # @rbs return: String
#   def method(a)
#   end
#
# @example EnforcedStyle: doc_style_and_return_annotation (default)
#   # bad - redundant annotation comment with parameters
#   # @rbs a: Integer
#   #: (Integer) -> String
#   def method(a)
#   end
#
#   # bad - redundant @rbs return annotation
#   # @rbs a: Integer
#   # @rbs return: String
#   def method(a) #: String
#   end
#
#   # good
#   # @rbs a: Integer
#   def method(a) #: String
#   end
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:82
class RuboCop::Cop::Style::RbsInline::RedundantTypeAnnotation < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Style::RbsInline::CommentParser
  include ::RuboCop::Cop::ConfigurableEnforcedStyle
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Style::RbsInline::SourceCodeHelper
  extend ::RuboCop::Cop::AutoCorrector

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:100
  def on_def(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:103
  def on_defs(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:94
  def on_new_investigation; end

  private

  # @rbs annotation:
  #   RBS::Inline::AST::Annotations::VarType |
  #   RBS::Inline::AST::Annotations::BlockType |
  #   RBS::Inline::AST::Annotations::SplatParamType |
  #   RBS::Inline::AST::Annotations::DoubleSplatParamType
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:178
  def add_offense_for_doc_style_param(annotation); end

  # @rbs annotation: RBS::Inline::AST::Annotations::ReturnType
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:209
  def add_offense_for_doc_style_return(annotation); end

  # @rbs comments: Array[Parser::Source::Comment]
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:163
  def add_offense_for_method_type_signature(comments); end

  # @rbs type: Symbol
  # @rbs value: untyped
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:188
  def add_offense_for_return(type, value); end

  # @rbs comment: Parser::Source::Comment
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:200
  def add_offense_for_trailing_return(comment); end

  # @rbs def_line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:115
  def check_parameter_redundancy(def_line); end

  # @rbs def_line: Integer
  # @rbs parameter_list_end_line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:145
  def check_return_type_redundancy(def_line, parameter_list_end_line); end

  # Returns the last line of the method parameter list (the closing ) line, or the def line if no parens).
  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:134
  def method_parameter_list_end_line(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:108
  def process(node); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:89
RuboCop::Cop::Style::RbsInline::RedundantTypeAnnotation::MSG_DOC_STYLE_PARAM = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:90
RuboCop::Cop::Style::RbsInline::RedundantTypeAnnotation::MSG_DOC_STYLE_RETURN = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:92
RuboCop::Cop::Style::RbsInline::RedundantTypeAnnotation::MSG_METHOD_TYPE_SIGNATURE = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/redundant_type_annotation.rb:91
RuboCop::Cop::Style::RbsInline::RedundantTypeAnnotation::MSG_TRAILING_RETURN = T.let(T.unsafe(nil), String)

# Checks for the presence or absence of `# rbs_inline:` magic comment.
#
# RBS::Inline supports two modes: opt-in (requires `# rbs_inline: enabled`) and
# opt-out (processes all files by default). This cop enforces consistency in which
# mode your codebase uses.
#
# @example EnforcedStyle: always (default)
#   # bad
#   # (no rbs_inline comment)
#   class Foo
#   end
#
#   # good
#   # rbs_inline: enabled
#   class Foo
#   end
#
#   # good
#   # rbs_inline: disabled
#   class Foo
#   end
#
# @example EnforcedStyle: never
#   # bad
#   # rbs_inline: enabled
#   class Foo
#   end
#
#   # good
#   # rbs_inline: disabled
#   class Foo
#   end
#
#   # good
#   # (no rbs_inline comment)
#   class Foo
#   end
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/require_rbs_inline_comment.rb:45
class RuboCop::Cop::Style::RbsInline::RequireRbsInlineComment < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/require_rbs_inline_comment.rb:52
  def on_new_investigation; end

  private

  # @rbs magic_comment: Parser::Source::Comment?
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/require_rbs_inline_comment.rb:79
  def check_always_style(magic_comment); end

  # @rbs magic_comment: Parser::Source::Comment?
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/require_rbs_inline_comment.rb:93
  def check_never_style(magic_comment); end

  # @rbs magic_comment: Parser::Source::Comment?
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/require_rbs_inline_comment.rb:74
  def disabled?(magic_comment); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/require_rbs_inline_comment.rb:105
  def find_insert_position; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/require_rbs_inline_comment.rb:116
  def find_last_comment_in_first_block; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/require_rbs_inline_comment.rb:67
  def find_rbs_inline_magic_comment; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/require_rbs_inline_comment.rb:134
  def first_line_range; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/require_rbs_inline_comment.rb:130
  def style; end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/require_rbs_inline_comment.rb:50
RuboCop::Cop::Style::RbsInline::RequireRbsInlineComment::MSG_FORBIDDEN = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/require_rbs_inline_comment.rb:49
RuboCop::Cop::Style::RbsInline::RequireRbsInlineComment::MSG_MISSING = T.let(T.unsafe(nil), String)

# Utility module for accessing processed source code information
# @rbs module-self RuboCop::Cop::Base
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/source_code_helper.rb:9
module RuboCop::Cop::Style::RbsInline::SourceCodeHelper
  include ::RuboCop::Cop::RangeHelp

  # Convert RBS::Inline annotation to Parser::Source::Range
  # @rbs annotation: RBS::Inline::AST::Annotations::t
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/source_code_helper.rb:62
  def annotation_range(annotation); end

  # @rbs line_number: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/source_code_helper.rb:38
  def blank_line?(line_number); end

  # @rbs pos: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/source_code_helper.rb:23
  def char_at(pos); end

  # Convert byte offset to character offset
  # @rbs byte_offset: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/source_code_helper.rb:14
  def character_offset(byte_offset); end

  # @rbs line: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/source_code_helper.rb:28
  def comment_at(line); end

  # Convert Prism::Comment to Parser::Source::Range
  # @rbs comment: Prism::Comment
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/source_code_helper.rb:56
  def comment_range(comment); end

  # @rbs line_number: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/source_code_helper.rb:44
  def line_range(line_number); end

  # Convert Prism::Location to Parser::Source::Range
  # @rbs location: Prism::Location
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/source_code_helper.rb:50
  def location_to_range(location); end

  # @rbs line_number: Integer
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/source_code_helper.rb:33
  def source_code_at(line_number); end
end

# IRB::Inline annotations comments for parameters should be matched to the parameters.
#
# @example
#   # bad
#   # @rbs unknown: String
#   def method(arg); end
#
#   # good
#   # @rbs arg: String
#   def method(arg); end
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/unmatched_annotations.rb:20
class RuboCop::Cop::Style::RbsInline::UnmatchedAnnotations < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Style::RbsInline::CommentParser
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Style::RbsInline::SourceCodeHelper

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/unmatched_annotations.rb:33
  def on_def(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/unmatched_annotations.rb:38
  def on_defs(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/unmatched_annotations.rb:42
  def on_investigation_end; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/unmatched_annotations.rb:27
  def on_new_investigation; end

  private

  # @rbs annotation: RBS::Inline::AST::Annotations::BlockType |
  #                  RBS::Inline::AST::Annotations::IvarType |
  #                  RBS::Inline::AST::Annotations::ReturnType |
  #                  RBS::Inline::AST::Annotations::VarType
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/unmatched_annotations.rb:141
  def add_offense_for(annotation); end

  # @rbs annotation: RBS::Inline::AST::Annotations::BlockType |
  #                  RBS::Inline::AST::Annotations::IvarType |
  #                  RBS::Inline::AST::Annotations::ReturnType |
  #                  RBS::Inline::AST::Annotations::VarType
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/unmatched_annotations.rb:126
  def annotation_name(annotation); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/unmatched_annotations.rb:113
  def args_for(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/unmatched_annotations.rb:80
  def arguments_for(node); end

  # @rbs node: RuboCop::AST::DefNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/unmatched_annotations.rb:60
  def process(node); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/unmatched_annotations.rb:25
RuboCop::Cop::Style::RbsInline::UnmatchedAnnotations::MSG = T.let(T.unsafe(nil), String)

# Checks that instance variables in classes/modules have RBS type annotations.
#
# Instance variables must either have a `# @rbs @ivar: Type` annotation
# or be covered by a typed `attr_reader/writer/accessor` declaration.
# Class-level (singleton) instance variables, assigned inside `class << self`
# or `def self.x`, must be annotated with `# @rbs self.@ivar: Type` instead.
#
# Only instance variables that are **assigned** within the class/module are checked.
# Read-only references are ignored because the variable may be defined in a parent class.
#
# @example
#   # bad
#   class Foo
#     def initialize
#       @baz = 1
#     end
#   end
#
#   # good
#   class Foo
#     # @rbs @baz: Integer
#
#     def initialize
#       @baz = 1
#     end
#   end
#
#   # good
#   class Foo
#     attr_reader :baz  #: Integer
#
#     def initialize
#       @baz = 1
#     end
#   end
#
#   # good (only read, may be defined in parent class)
#   class Foo
#     def bar
#       @baz
#     end
#   end
#
#   # good (class-level ivar annotated with `self.@`)
#   class Foo
#     # @rbs self.@instance: Foo
#
#     def self.instance
#       @instance ||= new
#     end
#   end
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:61
class RuboCop::Cop::Style::RbsInline::UntypedInstanceVariable < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Style::RbsInline::ASTUtils
  include ::RuboCop::Cop::Style::RbsInline::CommentParser
  include ::RuboCop::Cop::RangeHelp

  # @rbs node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:107
  def after_class(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:125
  def after_defs(_node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:113
  def after_module(node); end

  # @rbs _node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:122
  def after_sclass(_node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:83
  def civar_type_annotations; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:82
  def ivar_type_annotations; end

  # @rbs _node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:100
  def on_class(_node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:119
  def on_defs(_node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:92
  def on_investigation_end; end

  # @rbs node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:128
  def on_ivasgn(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:104
  def on_module(_node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:85
  def on_new_investigation; end

  # @rbs _node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:116
  def on_sclass(_node); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:138
  def on_send(node); end

  # @rbs! type scope = {
  #     typed_ivars: Set[Symbol],
  #     typed_class_ivars: Set[Symbol],
  #     assigned_ivars: Hash[Symbol, RuboCop::AST::Node],
  #     assigned_class_ivars: Hash[Symbol, RuboCop::AST::Node],
  #     singleton_depth: Integer
  #   }
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:81
  def scope_stack; end

  private

  # @rbs ann: RBS::Inline::AST::Annotations::IvarType
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:212
  def annotation_line(ann); end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:147
  def attr_method?(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:196
  def collect_ivar_type_annotations; end

  # @rbs node: RuboCop::AST::Node
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:185
  def collect_typed_ivars_for_scope(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:176
  def current_scope; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:172
  def pop_scope; end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:162
  def push_scope; end

  # @rbs node: RuboCop::AST::SendNode
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:152
  def register_attr_ivars(node); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:216
  def report_offenses; end

  # @rbs assigned: Hash[Symbol, RuboCop::AST::Node]
  # @rbs message_template: String
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:224
  def report_untyped(assigned, typed, message_template); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:180
  def singleton_context?; end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:71
RuboCop::Cop::Style::RbsInline::UntypedInstanceVariable::ATTR_METHODS = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:68
RuboCop::Cop::Style::RbsInline::UntypedInstanceVariable::MSG_CIVAR = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/untyped_instance_variable.rb:66
RuboCop::Cop::Style::RbsInline::UntypedInstanceVariable::MSG_IVAR = T.let(T.unsafe(nil), String)

# Checks that `@rbs` variable comments are followed by a blank line.
#
# RBS::Inline requires `@rbs` comments for instance variables, class variables,
# and class instance variables to be standalone comments, meaning they should
# not have any code immediately following them. A blank line after the variable
# comment ensures proper separation.
#
# @example
#   # bad
#   # @rbs @ivar: Integer
#   # @rbs @@cvar: Float
#   # @rbs self.@civar: String
#   def method
#   end
#
#   # good
#   # @rbs @ivar: Integer
#   # @rbs @@cvar: Float
#   # @rbs self.@civar: String
#
#   def method
#   end
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/variable_comment_spacing.rb:33
class RuboCop::Cop::Style::RbsInline::VariableCommentSpacing < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Style::RbsInline::SourceCodeHelper
  include ::RuboCop::Cop::Style::RbsInline::CommentParser
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/variable_comment_spacing.rb:41
  def on_new_investigation; end

  private

  # @rbs comment: Parser::Source::Comment
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/variable_comment_spacing.rb:54
  def check_variable_comment(comment); end

  # pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/variable_comment_spacing.rb:47
  def check_variable_comment_spacing; end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/variable_comment_spacing.rb:38
RuboCop::Cop::Style::RbsInline::VariableCommentSpacing::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/cop/style/rbs_inline/variable_comment_spacing.rb:39
RuboCop::Cop::Style::RbsInline::VariableCommentSpacing::VARIABLE_COMMENT_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rubocop-rbs_inline#lib/rubocop/rbs_inline/version.rb:4
module RuboCop::RbsInline; end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/rbs_inline.rb:7
class RuboCop::RbsInline::Error < ::StandardError; end

# A plugin that integrates RuboCop RBS Inline with RuboCop's plugin system.
#
# pkg:gem/rubocop-rbs_inline#lib/rubocop/rbs_inline/plugin.rb:8
class RuboCop::RbsInline::Plugin < ::LintRoller::Plugin
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/rbs_inline/plugin.rb:9
  def about; end

  # @rbs _context: untyped
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/rbs_inline/plugin.rb:25
  def rules(_context); end

  # @rbs context: untyped
  #
  # pkg:gem/rubocop-rbs_inline#lib/rubocop/rbs_inline/plugin.rb:20
  def supported?(context); end
end

# pkg:gem/rubocop-rbs_inline#lib/rubocop/rbs_inline/version.rb:5
RuboCop::RbsInline::VERSION = T.let(T.unsafe(nil), String)
