---
image: ruby:3.1

stages:
  - prepare
  - test
  - deploy

.cache: &cache_definition
  untracked: true
  key:
    files:
      - Gemfile.lock
  policy: pull
  paths:
    - 'vendor/'

before_script:
  - ruby --version
  - bundle --version
  - bundle config set --local jobs $(nproc)
  - bundle config set --local without ':doc'
  - bundle config set --local path vendor
  - bundle install --quiet

# Bundle stage
# ======================================

bundle:
  stage: prepare
  script:
    - echo "This job only fills the cache"
  cache:
    <<: *cache_definition
    policy: push

# Code lint
# ======================================

rubocop:
  stage: test
  script: bundle exec rubocop
  dependencies:
    - bundle

factory_bot_lint:
  stage: test
  script:
    - bundle exec rails db:test:prepare
    - bundle exec rake app:factory_bot:lint
  dependencies:
    - bundle

# Tests
# ======================================
rspec:
  stage: test
  script:
    - bundle exec rails db:test:prepare
    - bundle exec rspec
  dependencies:
    - bundle

# Gitlab pages
# ======================================
pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    # This step should be removed for Ruby > 3.1
    # See: https://github.com/jekyll/jekyll/issues/9563
    - gem update --system
    - bundle config unset --local without
    - bundle install --quiet
    - .gitlab/scripts/copy_documentation_files
    - .gitlab/scripts/build_documentation
  artifacts:
    paths:
      - public
