---
plugins:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  RubyInterpreters:
    - ruby
    - rake
  # Do not lint generated files
  Exclude:
    - bin/*
    - spec/dummy/bin/*
    - spec/dummy/db/schema.rb
    - coverage/**/*
    - vendor/**/*
  TargetRubyVersion: 3.2
  NewCops: enable

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - on_patch
        - on_get
        - on_put
        - on_post
        - on_delete
    Examples:
      Regular:
        - for_code
    Expectations:
      - test_response_of

FactoryBot/ConsistentParenthesesStyle:
  EnforcedStyle: omit_parentheses

# I prefer to type the whole calls instead of having the methods included in the
# tests
FactoryBot/SyntaxMethods:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 16.5
  Exclude:
    # Migrations
    - db/migrate/*.rb
    - spec/dummy/db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    # Migrations
    - db/migrate/*.rb
    - spec/dummy/db/migrate/*.rb
    # Routes
    - config/routes.rb
    - spec/dummy/config/routes.rb
    # Tasks
    - lib/tasks/*.rake
    - spec/dummy/lib/tasks/*.rake
    # Factories
    - spec/factories/*.rb
    - spec/dummy/spec/factories/*.rb
    # Other
    - spec/**/*_spec.rb
    - spec/support/shared_examples/**/*.rb

Metrics/ClassLength:
  Exclude:
    - db/migrate/*.rb
    - spec/dummy/db/migrate/*.rb

Metrics/MethodLength:
  Max: 12
  Exclude:
    - db/migrate/*.rb
    - spec/dummy/db/migrate/*.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb

Rails/DynamicFindBy:
  AllowedMethods:
    # In Actor model
    - find_by_account
    - find_by_federation_url

Rails/FilePath:
  EnforcedStyle: arguments

# :unprocessable_content was added in Rack 3.1, so until we require that, disable this check
RSpecRails/HttpStatusNameConsistency:
  Enabled: false

Rails/HttpStatusNameConsistency:
  Enabled: false

Rails/I18nLocaleTexts:
  Exclude:
    - spec/dummy/**/*

# Unsafe rule for Rails 8
# Re-enable when we don't support Rails 7 anymore and when the behavior stabilized
# Also, see
#  - https://github.com/rubocop/rubocop-rails/issues/1418 for an issue with Rubocop autocorrect on this rule
Rails/StrongParametersExpect:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    # Tasks
    - spec/tasks/*_spec.rb
    - spec/dummy/spec/tasks/*_spec.rb

RSpec/ExampleLength:
  Exclude:
    # Migrations
    - spec/migrations/*_spec.rb
    - spec/dummy/spec/migrations/*_spec.rb
    # Views are lengthy by design
    - spec/views/**/*_spec.rb
    - spec/dummy/spec/views/**/*_spec.rb

RSpec/ExpectActual:
  Exclude:
    # Routing specs
    - spec/routing/**/*_spec.rb
    - spec/dummy/spec/routing/**/*_spec.rb

RSpec/MultipleExpectations:
  Exclude:
    # Migrations
    - spec/migrations/*_spec.rb
    - spec/dummy/spec/migrations/*_spec.rb
    # Views spec have multiple expectations by design
    - spec/dummy/spec/views/**/*_spec.rb

RSpec/MultipleMemoizedHelpers:
  Exclude:
    # Migrations
    - spec/migrations/*_spec.rb
    - spec/dummy/spec/migrations/*_spec.rb

RSpec/NestedGroups:
  Max: 4

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/RepeatedDescription:
  Exclude:
    # Policies
    - spec/policies/**/*
    - spec/dummy/spec/policies/**/*

RSpec/RepeatedExample:
  Exclude:
    # Policies
    - spec/policies/**/*
    - spec/dummy/spec/policies/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/LeadingCommentSpace:
  Enabled: false
