#!/bin/bash

set -xe

set_title_and_order() {
  if [[ -n $3 ]];then
    sed -i "1s/^/---\ntitle: $2\nnav_order: $3\n---\n\n/" "$1"
  else
    sed -i "1s/^/---\ntitle: $2\n---\n\n/" "$1"
  fi
}

replace_md_links(){
  sed -i 's/.md)/)/' "$1"
}

cp README.md docs/index.md
sed -i '1s/^/---\n---\n\n/' docs/index.md
replace_md_links docs/index.md

cp CHANGELOG.md docs/
set_title_and_order docs/CHANGELOG.md Changelog 98
replace_md_links docs/CHANGELOG.md

cp MIGRATION_GUIDE.md docs/
set_title_and_order docs/MIGRATION_GUIDE.md "Migration guide" 99
replace_md_links docs/MIGRATION_GUIDE.md

cp LICENSE docs/LICENSE.md
set_title_and_order docs/LICENSE.md License 100
replace_md_links docs/LICENSE.md
