#!/bin/bash

set -xe

cp README.md docs/index.md
sed -i '1s/^/---\n---\n\n/' docs/index.md

cp CHANGELOG.md docs/
sed -i '1s/^/---\ntitle: Changelog\nnav_order: 98\n---\n\n/' docs/CHANGELOG.md

cp MIGRATION_GUIDE.md docs/
sed -i '1s/^/---\ntitle: Migration guide\nnav_order: 99\n---\n\n/' docs/MIGRATION_GUIDE.md

cp LICENSE docs/LICENSE.md
sed -i '1s/^/---\ntitle: License\nnav_order: 100\n---\n\n/' docs/LICENSE.md
