require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/federation/actors', type: :request do
  let(:user) { FactoryBot.create :user }
  let(:other_user) { FactoryBot.create :user }

  before do
    Federails::Following.create actor: user.federails_actor, target_actor: other_user.federails_actor
    Federails::Following.create actor: other_user.federails_actor, target_actor: user.federails_actor
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      get federails.server_actor_url(user.federails_actor), headers: { accept: Mime[:activitypub] }
      expect(response).to be_successful
    end

    it 'includes standard activitypub context' do
      get federails.server_actor_url(user.federails_actor), headers: { accept: Mime[:activitypub] }
      json = JSON.parse(response.body) # rubocop:disable Rails/ResponseParsedBody
      expect(json['@context']).to include('https://www.w3.org/ns/activitystreams')
    end

    it 'includes w3c security context' do
      get federails.server_actor_url(user.federails_actor), headers: { accept: Mime[:activitypub] }
      json = JSON.parse(response.body) # rubocop:disable Rails/ResponseParsedBody
      expect(json['@context']).to include('https://w3id.org/security/v1')
    end

    it 'includes additional context from actor' do # rubocop:todo RSpec/ExampleLength
      get federails.server_actor_url(user.federails_actor), headers: { accept: Mime[:activitypub] }
      json = JSON.parse(response.body) # rubocop:disable Rails/ResponseParsedBody
      expect(json['@context']).to include(
        {
          'attributionDomains' => {
            '@id'   => 'toot:attributionDomains',
            '@type' => '@id',
          },
          'toot'               => 'http://joinmastodon.org/ns#',
        }
      )
    end

    ACTIVITYPUB_CONTENT_TYPES.each do |accept|
      it "responds with LD in response to a #{accept} request" do
        get federails.server_actor_url(user.federails_actor), headers: { accept: accept }
        expect(response.content_type).to eq 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"; charset=utf-8'
      end
    end

    context 'when the actor is tombstoned' do
      before do
        user.federails_actor.tombstone!
      end

      it 'responds with a 410' do
        get federails.server_actor_url(user.federails_actor), headers: { accept: Mime[:activitypub] }
        expect(response).to have_http_status :gone
      end

      it 'responds with the Tombstone object' do
        get federails.server_actor_url(user.federails_actor), headers: { accept: Mime[:activitypub] }

        hash = JSON.parse(response.body) # rubocop:disable Rails/ResponseParsedBody

        aggregate_failures do
          expect(hash.keys).to include '@context', 'type', 'id', 'deleted', 'formerType'
        end
      end
    end
  end

  describe 'GET /followers' do
    it 'renders a successful response' do
      get federails.followers_server_actor_url(user.federails_actor), headers: { accept: Mime[:activitypub] }
      expect(response).to be_successful
    end

    ACTIVITYPUB_CONTENT_TYPES.each do |accept|
      it "responds with LD in response to a #{accept} request" do
        get federails.followers_server_actor_url(user.federails_actor), headers: { accept: accept }
        expect(response.content_type).to eq 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"; charset=utf-8'
      end
    end
  end

  describe 'GET /following' do
    it 'renders a successful response' do
      get federails.following_server_actor_url(user.federails_actor), headers: { accept: Mime[:activitypub] }
      expect(response).to be_successful
    end

    ACTIVITYPUB_CONTENT_TYPES.each do |accept|
      it "responds with LD in response to a #{accept} request" do
        get federails.following_server_actor_url(user.federails_actor), headers: { accept: accept }
        expect(response.content_type).to eq 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"; charset=utf-8'
      end
    end
  end
end
