require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/federation/actors', type: :request do
  let(:user) { FactoryBot.create :user }
  let(:other_user) { FactoryBot.create :user }

  before do
    Fedipub::Following.create actor: user.fedipub_actor, target_actor: other_user.fedipub_actor
    Fedipub::Following.create actor: other_user.fedipub_actor, target_actor: user.fedipub_actor
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      get fedipub.server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub] }
      expect(response).to be_successful
    end

    it 'rejects badly-signed requests' do
      get fedipub.server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub], signature: 'poop' }
      expect(response).to have_http_status :unauthorized
    end

    it 'rejects unsigned requests when signatures are required' do
      allow(Fedipub::ServerController).to receive(:require_signature?).and_return(true)
      get fedipub.server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub] }
      expect(response).to have_http_status :unauthorized
    end

    it 'includes standard activitypub context' do
      get fedipub.server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub] }
      json = response.parsed_body
      expect(json['@context']).to include('https://www.w3.org/ns/activitystreams')
    end

    it 'includes w3c security context' do
      get fedipub.server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub] }
      json = response.parsed_body
      expect(json['@context']).to include('https://w3id.org/security/v1')
    end

    it 'includes additional context from actor' do # rubocop:todo RSpec/ExampleLength
      get fedipub.server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub] }
      json = response.parsed_body
      expect(json['@context']).to include(
        {
          'attributionDomains' => {
            '@id'   => 'toot:attributionDomains',
            '@type' => '@id',
          },
          'toot'               => 'http://joinmastodon.org/ns#',
        }
      )
    end

    ACTIVITYPUB_CONTENT_TYPES.each do |accept|
      it "responds with LD in response to a #{accept} request" do
        get fedipub.server_actor_url(user.fedipub_actor), headers: { accept: accept }
        expect(response.content_type).to eq 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"; charset=utf-8'
      end
    end

    context 'when the actor is tombstoned' do
      before do
        user.fedipub_actor.tombstone!
      end

      it 'responds with a 410' do
        get fedipub.server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub] }
        expect(response).to have_http_status :gone
      end

      it 'responds with the Tombstone object' do
        get fedipub.server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub] }

        hash = response.parsed_body

        aggregate_failures do
          expect(hash.keys).to include '@context', 'type', 'id', 'deleted', 'formerType'
        end
      end
    end
  end

  describe 'GET /followers' do
    it 'renders a successful response' do
      get fedipub.followers_server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub] }
      expect(response).to be_successful
    end

    it 'rejects badly-signed requests' do
      get fedipub.followers_server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub], signature: 'poop' }
      expect(response).to have_http_status :unauthorized
    end

    it 'rejects unsigned requests when signatures are required' do
      allow(Fedipub::ServerController).to receive(:require_signature?).and_return(true)
      get fedipub.followers_server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub] }
      expect(response).to have_http_status :unauthorized
    end

    ACTIVITYPUB_CONTENT_TYPES.each do |accept|
      it "responds with LD in response to a #{accept} request" do
        get fedipub.followers_server_actor_url(user.fedipub_actor), headers: { accept: accept }
        expect(response.content_type).to eq 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"; charset=utf-8'
      end
    end
  end

  describe 'GET /following' do
    it 'renders a successful response' do
      get fedipub.following_server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub] }
      expect(response).to be_successful
    end

    it 'rejects badly-signed requests' do
      get fedipub.following_server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub], signature: 'poop' }
      expect(response).to have_http_status :unauthorized
    end

    it 'rejects unsigned requests when signatures are required' do
      allow(Fedipub::ServerController).to receive(:require_signature?).and_return(true)
      get fedipub.following_server_actor_url(user.fedipub_actor), headers: { accept: Mime[:activitypub] }
      expect(response).to have_http_status :unauthorized
    end

    ACTIVITYPUB_CONTENT_TYPES.each do |accept|
      it "responds with LD in response to a #{accept} request" do
        get fedipub.following_server_actor_url(user.fedipub_actor), headers: { accept: accept }
        expect(response.content_type).to eq 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"; charset=utf-8'
      end
    end
  end

  describe 'when fetching Application actor' do
    it 'renders a successful response' do
      get fedipub.server_actor_url(Fedipub::Actor.application_actor), headers: { accept: Mime[:activitypub] }
      expect(response).to be_successful
    end

    it 'fetches the correct application actor' do
      get fedipub.server_actor_url(Fedipub::Actor.application_actor), headers: { accept: Mime[:activitypub] }
      expect(response.parsed_body['preferredUsername']).to eq '__application'
    end

    it 'includes a proper id' do
      get fedipub.server_actor_url(Fedipub::Actor.application_actor), headers: { accept: Mime[:activitypub] }
      expect(response.parsed_body['id']).to match(%r{http://localhost/federation/actors/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}})
    end

    it 'fetches the application actor\'s public key' do
      get fedipub.server_actor_url(Fedipub::Actor.application_actor), headers: { accept: Mime[:activitypub] }
      expect(response.parsed_body['publicKey']['publicKeyPem']).to be_present
    end

    it 'allows unsigned requests' do
      pending 'implementation of configuration option for requiring signatures'
      allow(Fedipub::ServerController).to receive(:require_signature?).and_return(true)
      get fedipub.server_actor_url(Fedipub::Actor.application_actor), headers: { accept: Mime[:activitypub] }
      expect(response).to be_successful
    end

    context 'when checking "implements" information (FEP-844e)' do
      let(:implemented_hrefs) { response.parsed_body['implements']&.pluck('href') }

      before do
        get fedipub.server_actor_url(Fedipub::Actor.application_actor), headers: { accept: Mime[:activitypub] }
      end

      it 'implements ActivityPub' do
        expect(implemented_hrefs).to include 'https://www.w3.org/TR/activitypub/'
      end

      it 'implements RFC9421' do
        expect(implemented_hrefs).to include 'https://datatracker.ietf.org/doc/html/rfc9421'
      end

      it 'implements draft-cavage-12' do
        expect(implemented_hrefs).to include 'https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures-12'
      end

      it 'implements FEP-844e (capability discovery)' do
        expect(implemented_hrefs).to include 'https://w3id.org/fep/844e'
      end

      it 'implements FEP-2677 (application actor + nodeinfo discovery)' do
        expect(implemented_hrefs).to include 'https://w3id.org/fep/2677'
      end

      it 'implements FEP-d556 (Server-Level Actor Discovery Using WebFinger)' do
        expect(implemented_hrefs).to include 'https://w3id.org/fep/d556'
      end
    end
  end
end
