require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/federation/followings', type: :request do
  # Federation::Following. As you add validations to Federation::Following, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /show' do
    let(:actor) { FactoryBot.create(:user).federails_actor }
    let(:target_actor) { FactoryBot.create(:user).federails_actor }
    let(:following) { FactoryBot.create :following, actor: actor, target_actor: target_actor }

    it 'renders a successful response' do
      get federails.server_actor_following_url(actor, following), headers: { accept: Mime[:activitypub] }
      expect(response).to be_successful
    end

    ACTIVITYPUB_CONTENT_TYPES.each do |accept|
      it "responds with LD in response to a #{accept} request" do
        get federails.server_actor_following_url(actor, following), headers: { accept: accept }
        expect(response.content_type).to eq 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"; charset=utf-8'
      end
    end
  end
end
