require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/federation/followings', type: :request do
  describe 'GET /show' do
    let(:actor) { FactoryBot.create(:user).federails_actor }
    let(:target_actor) { FactoryBot.create(:user).federails_actor }
    let(:following) { FactoryBot.create :following, actor: actor, target_actor: target_actor }

    it 'renders a successful response' do
      get federails.server_actor_following_url(actor, following), headers: { accept: Mime[:activitypub] }
      expect(response).to be_successful
    end

    ACTIVITYPUB_CONTENT_TYPES.each do |accept|
      it "responds with LD in response to a #{accept} request" do
        get federails.server_actor_following_url(actor, following), headers: { accept: accept }
        expect(response.content_type).to eq 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"; charset=utf-8'
      end
    end

    it 'returns a Follow object with required fields' do
      get federails.server_actor_following_url(actor, following), headers: { accept: Mime[:activitypub] }
      json = JSON.parse(response.body) # rubocop:disable Rails/ResponseParsedBody
      aggregate_failures do
        expect(json['type']).to eq 'Follow'
        expect(json['id']).to eq following.federated_url
        expect(json['actor']).to eq actor.federated_url
        expect(json['object']).to eq target_actor.federated_url
      end
    end
  end
end
