# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedMountedHelpers`.
# Please instead update this file by running `bin/tapioca dsl GeneratedMountedHelpers`.


class Fedipub::Engine::GeneratedRoutesProxy < ::ActionDispatch::Routing::RoutesProxy
  include Fedipub::Engine::GeneratedPathHelpersModule
  include Fedipub::Engine::GeneratedUrlHelpersModule
end

module GeneratedMountedHelpers
  sig { returns(Fedipub::Engine::GeneratedRoutesProxy) }
  def fedipub; end

  sig { returns(GeneratedRoutesProxy) }
  def main_app; end
end

class GeneratedRoutesProxy < ::ActionDispatch::Routing::RoutesProxy
  include GeneratedPathHelpersModule
  include GeneratedUrlHelpersModule
end
