# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Fedipub::Engine::GeneratedPathHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl Fedipub::Engine::GeneratedPathHelpersModule`.


module Fedipub::Engine::GeneratedPathHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def accept_client_following_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def client_activities_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def client_actor_activities_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def client_actor_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def client_actors_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def client_feed_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def client_following_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def client_followings_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def featured_server_actor_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def featured_tags_server_actor_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def feed_client_activities_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def follow_client_followings_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def followers_server_actor_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def following_server_actor_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def host_meta_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def liked_server_actor_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def lookup_client_actors_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_client_following_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def node_info_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def server_actor_activity_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def server_actor_following_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def server_actor_inbox_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def server_actor_outbox_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def server_actor_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def server_published_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def server_shared_inbox_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def show_node_info_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def webfinger_path(*args); end
end
